### ISSUE TITLE
Common: Windows port of wthread_cond_wait passes incorrect value to LeaveCriticalSection

### ISSUE THREAD

**Issue by MattMulhern** [OpenMAMA/OpenMAMA#10]
**Replacing  [bz-112](http://bugs.openmama.org/show_bug.cgi?id=112)**
The Windows port of wthread_cond_wait passes a pointer to a LPCRITICAL_SECTION to both the LeaveCriticalSection and EnterCriticalSection functions. These should both be LPCRITICAL_SECTIONS themselves.

Building on Windows with VS results in the following warnings:

```bash
1>windows\port.c(135): warning C4047: 'function' : 'LPCRITICAL_SECTION' differs in levels of indirection from 'LPCRITICAL_SECTION *'
1>windows\port.c(135): warning C4024: 'LeaveCriticalSection' : different types for formal and actual parameter 1
1>windows\port.c(138): warning C4047: 'function' : 'LPCRITICAL_SECTION' differs in levels of indirection from 'LPCRITICAL_SECTION *'
1>windows\port.c(138): warning C4024: 'EnterCriticalSection' : different types for formal and actual parameter 1
```

**Comment by fquinner** [comment]
From BZ ticket:

> Luckily, at present at least, the invalid stuff is just in the function prototype, and because it's dealing with pointers there shouldn't actually be an issue with the conversion. The fix should be straightforward as well - simply change the prototype to:
> 
> ```
> COMMONExpDLL DWORD
> wthread_cond_wait( HANDLE *event, LPCRITICAL_SECTION cs);
> ```

**Comment by fquinner** [comment]
#204
