### ISSUE TITLE
Create wiki page to help guide bridge developers on how to use dynamic bridge loading

### ISSUE THREAD

**Issue by fquinner** [OpenMAMA/OpenMAMA#107]
We need to put together a wiki page detailing the work that is required for bridge developers to migrate to the dynamic bridge loading mechanism.

**Comment by dmagOM** [comment]
Yeah, makes sense. There's very little that's actually *required* for it to work, but there are certainly things bridge developers need to be aware of, and some new best practices to take into account. I know we made some test changes to the Qpid bridge as part of this, but it would be good to formalize those, and perhaps use them as before/after examples.

Off the top of my head:
- Remove allocation and free'ing of the memory for the bridgeImpl structure. 
- Implement new 'init' methods.
- Review bridge method names and ensure they match those being searched for by the new library search mechanism.
    - If custom bridge impl population has been utilized, this should be ported to work with the new features (I am not aware of any real world examples of this, but I expect complex bridges may have some configurable options in this area).
- Ensure bridge methods have external visibility on Windows platforms.

It would probably be useful to describe the process taken by the new loading mechanism as well, just to give a bit of clarity to people unfamiliar with it.

**Comment by MattMulhern** [comment]
added new wiki page [here](https://github.com/OpenMAMA/OpenMAMA/wiki/Dynamic-Bridge-Loading)

**Comment by fquinner** [comment]
Yup looks good now - thanks
