### ISSUE TITLE
MamaTimerTestCPP.ForTimer Unit Test Displays warning for Qpid 

### ISSUE THREAD

**Issue by dmagOM** [OpenMAMA/OpenMAMA#109]
OS: Fedora 23 
QPID: 0.10 (from Fedora RPM Repos)
OM Branch: next 

When I run the MamaTimerTestCPP.ForTimer UnitTest, I'm seeing a lot of failed reset notifications, followed by what appears like a hang in the unit test:

    [damian@localhost omama-test-env]$ UnitTestMamaCPP -m qpid -p qpidmsg --gtest_filter=MamaTimerTestCPP.ForTimer
    Starting...
    Middleware = qpid
    Running tests
    Note: Google Test filter = MamaTimerTestCPP.ForTimer
    [==========] Running 1 test from 1 test case.
    [----------] Global test environment set-up.
    [----------] 1 test from MamaTimerTestCPP
    [ RUN      ] MamaTimerTestCPP.ForTimer
    2016-01-24 00:52:09: 
    ********************************************************************************
    Note: This build of the MAMA API is not enforcing entitlement checks.
    Please see the Licensing file for details
    **********************************************************************************
    2016-01-24 00:52:09: Failed to reset Qpid underlying timer [-1].
    2016-01-24 00:52:09: Failed to reset Qpid underlying timer [-1].
    ...
    2016-01-24 00:52:09: Failed to reset Qpid underlying timer [-1].

Interacting with the console seems to wake the test up again after a short period.

    ...
    2016-01-24 00:54:00: Failed to reset Qpid underlying timer [-1].
    2016-01-24 00:54:00: Failed to reset Qpid underlying timer [-1].
    [       OK ] MamaTimerTestCPP.ForTimer (10023 ms)
    [----------] 1 test from MamaTimerTestCPP (10024 ms total)
    
    [----------] Global test environment tear-down
    [==========] 1 test from 1 test case ran. (10024 ms total)
    [  PASSED  ] 1 test.

The error message being printed comes from the `timer.c` code in the Qpid bridge, where the most recent changes were from this: a4a684e3ab0ce1ec6a2d5eff3c95c29c7cffee2f 

Need to do some more work to determine if that's the route cause or not, but it raising here to track anyway,

D

**Comment by fquinner** [comment]
As discussed, I can recreate this but only if I restrict the execution environment to a single core (e.g. with numactl).

**Comment by dmagOM** [comment]
Yep, it appears we end up passing NULL timers into the `qpidBridgeMamaTimer_reset` method. I'm not sure why yet, but it only seems to happen when restricted to a single core, which makes me think it's some sort of race condition. 

We don't see it under GDB either, and helgrind isn't throwing anything suspicious.

**Comment by fquinner** [comment]
I stuck a raise(6) into the line with the error logging to generate a core:
```
(gdb) bt
#0  0x00007f292e4e5a98 in raise () from /lib64/libc.so.6
#1  0x00007f292de7d342 in qpidBridgeMamaTimer_reset (timer=0xf1eae0) at mama/c_cpp/src/c/bridge/qpid/timer.c:238
#2  0x00007f292de7d394 in qpidBridgeMamaTimerImpl_timerCallback (timer=<optimized out>, closure=0xf1eae0) at mama/c_cpp/src/c/bridge/qpid/timer.c:324
#3  0x00007f292de807bf in dispatchEntry (closure=0xee8810) at common/c_cpp/src/c/timers.c:182
#4  0x00007f292e29b60a in start_thread () from /lib64/libpthread.so.0
#5  0x00007f292e5b3a4d in clone () from /lib64/libc.so.6
(gdb) thread apply all bt

Thread 4 (Thread 0x7f2929fbd700 (LWP 7442)):
#0  0x00007f292e5b3a11 in clone () from /lib64/libc.so.6
#1  0x00007f292e29b540 in ?? () from /lib64/libpthread.so.0
#2  0x00007f2929fbd700 in ?? ()
#3  0x0000000000000000 in ?? ()

Thread 3 (Thread 0x7f292fe71740 (LWP 7439)):
#0  0x00007f292e2a393a in __lll_unlock_wake () from /lib64/libpthread.so.0
#1  0x00007f292e29eecf in pthread_mutex_unlock () from /lib64/libpthread.so.0
#2  0x00007f292de80f8b in createTimer (timer=timer@entry=0xf1eae0, heap=0xee8810, cb=cb@entry=0x7f292de7d370 <qpidBridgeMamaTimerImpl_timerCallback>, timeout=timeout@entry=0x7ffdaf37b760, closure=closure@entry=0xf1eae0) at common/c_cpp/src/c/timers.c:296
#3  0x00007f292de7d1fe in qpidBridgeMamaTimer_create (result=0xf1eac0, nativeQueueHandle=0xee7130, action=0x7f292f3678c0 <Wombat::MamaTimer::onTimerTick(mamaTimerImpl*, void*)>, onTimerDestroyed=0x7f292f5cbaf0 <mamaTimer_onTimerDestroyed>, interval=<optimized out>, 
    parent=0xf1eab0, closure=0xf1ea80) at mama/c_cpp/src/c/bridge/qpid/timer.c:148
#4  0x00007f292f5cbcde in mamaTimer_start (result=0xf1eab0, action=0x7f292f3678c0 <Wombat::MamaTimer::onTimerTick(mamaTimerImpl*, void*)>, interval=0, closure=0xf1ea80) at mama/c_cpp/src/c/timer.c:169
#5  0x00007f292f3677f3 in Wombat::MamaTimer::create (this=0xed6290, queue=0xeecd60, callback=0x7ffdaf37b840, interval=0, closure=0xed6220) at mama/c_cpp/src/cpp/MamaTimer.cpp:227
#6  0x000000000040b28b in MamaTimerTestCPP_ForTimer_Test::TestBody (this=0xed6220) at mama/c_cpp/src/gunittest/cpp/MamaTimerTest.cpp:180
#7  0x00007f292fa65993 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) () from /lib64/libgtest.so.0
#8  0x00007f292fa5d74a in testing::Test::Run() () from /lib64/libgtest.so.0
#9  0x00007f292fa5d898 in testing::TestInfo::Run() () from /lib64/libgtest.so.0
#10 0x00007f292fa5d975 in testing::TestCase::Run() () from /lib64/libgtest.so.0
#11 0x00007f292fa5e2df in testing::internal::UnitTestImpl::RunAllTests() () from /lib64/libgtest.so.0
#12 0x00007f292fa65e73 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) () from /lib64/libgtest.so.0
#13 0x00007f292fa5da40 in testing::UnitTest::Run() () from /lib64/libgtest.so.0
#14 0x0000000000403cb1 in RUN_ALL_TESTS () at /usr/include/gtest/gtest.h:2288
#15 main (argc=5, argv=0x7ffdaf37bb78) at mama/c_cpp/src/gunittest/cpp/MainUnitTestCpp.cpp:79

Thread 2 (Thread 0x7f292abe9700 (LWP 7441)):
#0  0x00007f292e2a2e57 in do_futex_wait.constprop () from /lib64/libpthread.so.0
#1  0x00007f292e2a2f04 in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
#2  0x00007f292e2a2faa in sem_wait@@GLIBC_2.2.5 () from /lib64/libpthread.so.0
#3  0x00007f292de7ae60 in qpidBridgeMamaIoImpl_dispatchThread (closure=<optimized out>) at mama/c_cpp/src/c/bridge/qpid/io.c:246
#4  0x00007f292e29b60a in start_thread () from /lib64/libpthread.so.0
#5  0x00007f292e5b3a4d in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f292b3ea700 (LWP 7440)):
#0  0x00007f292e4e5a98 in raise () from /lib64/libc.so.6
#1  0x00007f292de7d342 in qpidBridgeMamaTimer_reset (timer=0xf1eae0) at mama/c_cpp/src/c/bridge/qpid/timer.c:238
#2  0x00007f292de7d394 in qpidBridgeMamaTimerImpl_timerCallback (timer=<optimized out>, closure=0xf1eae0) at mama/c_cpp/src/c/bridge/qpid/timer.c:324
#3  0x00007f292de807bf in dispatchEntry (closure=0xee8810) at common/c_cpp/src/c/timers.c:182
    #4  0x00007f292e29b60a in start_thread () from /lib64/libpthread.so.0
    #5  0x00007f292e5b3a4d in clone () from /lib64/libc.so.6
```

Turns out it adds a timer element before populating the return value, so when the impl is back referenced in the callback, it hasn't actually been populated yet in the other thread. Bug was introduced in a4a684e3ab0ce1ec6a2d5eff3c95c29c7cffee2f. Should be a small fix in timers.c.

**Comment by fquinner** [comment]
Now a pull request: #118
