### ISSUE TITLE
MAMA JAVA: Fix issues with Java Docs

### ISSUE THREAD

**Issue by MattMulhern** [OpenMAMA/OpenMAMA#13]
**Replacing [BZ-141](http://bugs.openmama.org/show_bug.cgi?id=141)**

There are a number of issues with the currently generated JavaDocs files from OpenMAMA. Specifically:
- Header and footer image cannot be found.
- Content needs update to reflect name 'OpenMAMA' rather than MAMA.

Most of these changes should be straightforward, and can be made to the mama/jni/SConscript and mama/jni/SConscript.win files.

**Comment by fquinner** [comment]
This should be fixed now as part of other changes.
