### ISSUE TITLE
Ensure that MAMA properties loading happens before _init

### ISSUE THREAD

**Issue by fquinner** [OpenMAMA/OpenMAMA#135]
Need to verify / correct if this is not already the case. I know some bridges have some hacks in place to work around this atm which they would prefer to get rid of.

**Comment by dmagOM** [comment]
Mmmm, I believe this should have been in the `mamaInternal_init` function, but it doesn't appear to have been added. Should be safe enough to add anyway.

**Comment by fquinner** [comment]
Can confirm this already works in the middleware bridge. It will not work for the payload bridge where the user has done something like this:
```
mama_loadPayloadBridge
mama_open
```

However, it will work if the payload bridge is loaded *by* the middleware bridge.

This is because the open stage is the first point where the properties are definitely introduced and that's the first point in the application code where the properties configuration file is known (because open could alternatively have been called using `mama_openWithProperties`.

I think a graceful alternative to address this is to make the list of payloads to load configurable, so something like this:

```
mama.payload.qpidmsg.autoload = True
mama.payload.avismsg.autoload = True
```

But that's a job for the next release. I'll raise a ticket for that now and close this off.
