### ISSUE TITLE
OpenMAMA scons fails to build with multiple build types

### ISSUE THREAD

**Issue by MattMulhern** [OpenMAMA/OpenMAMA#15]
**Replacing [BZ-193](http://bugs.openmama.org/show_bug.cgi?id=193)**
When attempting to build OpenMAMA with scons it will fail to build when using multiple build types.
Specifically within the omama.conf

```bash
buildtype = 'all'
```
or
```bash
buildtype = 'dynamic,dynamic-debug'
```
The following error is generated:
> Install file: "mama\c_cpp\src\examples\c\Makefile.sample" as "openmama_install_2.3.2\examples\mama\c\Makefile.sample"
> scons: *** [openmama_install_2.3.2\examples\mama\c\Makefile.sample] AssertionError : Installing source ['mama\\c_cpp\\src\\examples\\c\\Makefile.sample', 'mama\\c_cpp\\src\\examples\\c\\Makefile.sample'] into target ['openmama_install_2.3.2\\examples\\mama\\c\\Makefile.sample']: target and source lists must have same length.
> Traceback (most recent call last):
>   File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.3.0\SCons\Action.py", line 1062, in execute
>     result = self.execfunction(target=target, source=rsources, env=env)
>   File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.3.0\SCons\Tool\install.py", line 215, in installFunc
>     "Installing source %s into target %s: target and source lists must have same length."%(list(map(str, source)), list(map(str, target)))
> AssertionError: Installing source ['mama\\c_cpp\\src\\examples\\c\\Makefile.sample', 'mama\\c_cpp\\src\\examples\\c\\Makefile.sample'] into target ['openmama_install_2.3.2\\examples\\mama\\c\\Makefile.sample']: target and source lists must have same length.
> scons: building terminated because of errors.

**Comment by fquinner** [comment]
Succeeded fix submitted in #195
