### ISSUE TITLE
Plugin shutdown missing from mama_close()

### ISSUE THREAD

**Issue by fquinner** [OpenMAMA/OpenMAMA#151]
As reported by Reed:

...the plugin shutdown is missing from mama_close...

```
       /* This will shutdown all plugins */
       mama_shutdownPlugins();
```
This looks to be an oversight introduced by the dynamic bridge loading changes merging - will need this to be reinstated.

**Comment by MattMulhern** [comment]
Opened PR #152. Closing this off to track changes on PR.
