### ISSUE TITLE
QPID: Cannot subscribe to same source (peer to peer) more than twice.

### ISSUE THREAD

**Issue by MattMulhern** [OpenMAMA/OpenMAMA#153]
Can't seem to have more than 2 simultaneous subscribers using qpid.

### recreation steps:

1. **Publisher**: mamapublisherc -m qpid -tport pub -S MAMA_SRC -s mama_sym
2. **Subscriber 1**: mamasubscriberc -m qpid -tport sub1 -S MAMA_SRC -s mama_sym
3. **Subscriber 2**: mamasubscriberc -m qpid -tport sub2 -S MAMA_SRC -s mama_sym
4. **Subscriber 3**: mamasubscriberc -m qpid -tport sub3 -S MAMA_SRC -s mama_sym

**Comment by fquinner** [comment]
Can recreate this behaviour with a small native qpid proton application. Looks like it's most likely a bug or limitation there. Going to write up my findings and post to proton folks.

**Comment by fquinner** [comment]
Qpid proton mailing list entry: http://qpid.2158936.n2.nabble.com/Deadlock-in-pn-messenger-send-when-using-more-than-2-publishers-td7641239.html

**Comment by fquinner** [comment]
Raised Qpid Proton issue: https://issues.apache.org/jira/browse/PROTON-1169

**Comment by fquinner** [comment]
https://issues.apache.org/jira/browse/PROTON-1169?focusedCommentId=15286378&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15286378

**Comment by fquinner** [comment]
Workaround didn't work, so taking this out of upcoming release. Might even just refuse to support at all as it's only not working because of a bug in proton and broker is the preferred option anyway. Tried using pn_messenger_work but i'd like another crack before giving up entirely.

**Comment by fquinner** [comment]
It seems no matter what approach is taken this doesn't want to work. Recommendation here will be simply to use a broker, or possibly the zmq bridge if support for point to point for fan-in / fan-out is required.
