### ISSUE TITLE
QPID: failing to get dictionary on subscription creation when using broker implementation.

### ISSUE THREAD

**Issue by MattMulhern** [OpenMAMA/OpenMAMA#154]
Mamalistenc failing to get a dictionary leading to a timeout.
> Created subscription: source=[MATT], symbol=[DE000CT9JR44.EUR.XAMS]
> 2016-03-07 16:43:11: (d286740) : mamaSubscription::setup() DE000CB74TM9.EUR.XBRU: setup Marketdata subscription (0x2713de0)
> 2016-03-07 16:43:11: (d286740) : mamaSubscription_initialize(): Initializing subscription (0x2713de0) for source=MATT, symbol=DE000CB74TM9.EUR.XBRU (DE000CB74TM9.EUR.XBRU)
> 2016-03-07 16:43:11: (d286740) : qpidBridgeMamaSubscriptionImpl_generateSubjectKey(): S.
> 2016-03-07 16:43:11: (d286740) : qpidBridgeMamaSubscriptionImpl_generateSubjectKey(): T.
> 2016-03-07 16:43:11: (d286740) : qpidBridgeMamaSubscription_create(): created interest for MATT.DE000CB74TM9.EUR.XBRU.
> 2016-03-07 16:43:11: (d286740) : imageRequest_sendRequest (): DE000CB74TM9.EUR.XBRU: requesting initial value, dictionary, or recap.
> 2016-03-07 16:43:11: (d286740) : imageRequest::requestAction (): DE000CB74TM9.EUR.XBRU: requesting initial value, dictionary,or recap (request=0x27181e0; timeoutTimer=0x27878b0).
> 2016-03-07 16:43:11: (d286740) : Subscription 0x2713de0 is now at state MAMA_SUBSCRIPTION_ACTIVATED.
> Created subscription: source=[MATT], symbol=[DE000CB74TM9.EUR.XBRU]
> 2016-03-07 16:43:11: (7b17700) : qpidBridgeMamaTransportImpl_dispatchThread(): recv-ed
> 2016-03-07 16:43:11: (7b17700) : qpidBridgeMamaTransportImpl_dispatchThread(): error getting message, (null)

### Recreation details
1. **start broker**: `qpidd --auth no --topic-patterns MAMA.*  -t`
2. **start publisher**: `capturereplayc  -m qpid -tport matt_broker -S MATT -f playback.mplay -dictionary dict.dict`
3. **start subscriber**: `mamalistenc -S MATT -m qpid -tport matt_broker -f syms.txt`
4. *bounce your subscriber a few times as is infrequent*

### Summary
Within `qpidBridgeMamaTransportImpl_dispatchThread() we call:  `pn_messenger_get` to fetch a message:
```
            if (pn_messenger_get (impl->mIncoming, msgNode->mMsg))
            {
                mama_log (MAMA_LOG_LEVEL_ERROR,
                          "qpidBridgeMamaTransportImpl_dispatchThread(): "
                          "error getting message, %s",
                          PN_MESSENGER_ERROR (impl->mIncoming));
                impl->mQpidDispatchStatus = MAMA_STATUS_PLATFORM;
                return NULL;
            }
```

This returning an error code (PN_EOS: -1). which according to the [qpid documentation](https://qpid.apache.org/releases/qpid-proton-0.6/protocol-engine/c/api/messenger_8h.html#a35e431048a46e6f879f300d273102c9e) implies that nothing receive which shouldn't be the case at this point.

**Comment by fquinner** [comment]
This looks like it was resolved by bf95e81b9e6de4dcea6572f129ee07719d14b927
