### ISSUE TITLE
QPID: Broker error logging with "multiple management objects with the same identifier"

### ISSUE THREAD

**Issue by MattMulhern** [OpenMAMA/OpenMAMA#155]
When using the qpid broker, it seems to be complaining about the internal uuid's it uses to track connections:
> 2016-02-05 10:05:00 [Management] error Detected two management objects with the same identifier: 0-155-1--158(org.apache.qpid.broker:incoming:AA178841-56A6-4611-98E6-0228927D9B53,sender-xxx)

This seems similar to some issues already raised with QPID:
[QPID-3666](https://issues.apache.org/jira/browse/QPID-3666) fixed in versions > 0.15
[QPID-3356](https://issues.apache.org/jira/browse/QPID-3356) roughly explains the purpose of the message

The recurring theme is that the "exchange+queue+bindingkey" used to create the URL must be unique, so either we're not building up the URL we think we are, or some handling is going wrong within the proton libs.

**Comment by fquinner** [comment]
Going to go ahead and close this off because it doesn't effect functionality and if an invalid URL is being exchanged somewhere, it's entirely Qpid Proton's problem because we have no control over that mechanism - it's handled by qpid proton and the broker.
