### ISSUE TITLE
Missing transport status in C++ code

### ISSUE THREAD

**Issue by MattMulhern** [OpenMAMA/OpenMAMA#16]
**Replacing [bz-195](http://bugs.openmama.org/show_bug.cgi?id=195)**
In MamaTransport.cpp the following status codes are missing:
- MAMA_TRANSPORT_CONNECT_FAILED
- MAMA_TRANSPORT_WRITE_QUEUE_LOW_WATER_MARK
- MAMA_TRANSPORT_WRITE_QUEUE_HIGH_WATER_MARK

**Comment by fquinner** [comment]
Actually a bigger change than I thought because this will involve wiring in currently missing callbacks in multiple language so de-scoping for next release.

**Comment by fquinner** [comment]
Original thread: https://lists.openmama.org/pipermail/openmama-dev/2015-March/thread.html#1465

**Comment by fquinner** [comment]
Won't fix - please submit a new PR if this is of interest.
