### ISSUE TITLE
COMMON: Compiler warning for incorrect NULL check in MRSWLock.c

### ISSUE THREAD

**Issue by MattMulhern** [OpenMAMA/OpenMAMA#17]
**Replacing [bz-121](http://bugs.openmama.org/show_bug.cgi?id=121)**
Building OpenMAMA with clang emits the following warning indicating that the if statement will always execute to true:

```bash
WARNING:: common/c_cpp/src/c/MRSWLock.c:200:13: warning: comparison of address of 'lock->m_noLocksEvent' not equal to a null pointer is always true
[-Wtautological-pointer-compare]
                if(&lock->m_noLocksEvent != NULL)
```

This should be fixed. Patch attached to Bugzilla.

**Comment by fquinner** [comment]
Already fixed: https://github.com/OpenMAMA/OpenMAMA/commit/366294b1a0fdf88a4d7ddae889f136c0ca55ae44#diff-ed8791c5c62a925f53e297d05cff7e1f
