### ISSUE TITLE
MAMA/COMMON: Core in list callbacks when creating

### ISSUE THREAD

**Issue by MattMulhern** [OpenMAMA/OpenMAMA#18]
**Replacing [bz-170](http://bugs.openmama.org/show_bug.cgi?id=170)**

We have a report of a crash in MAMA when dereferencing a null pointer in
list_for_each(wList list, wListCallback cb, void* closure) from
/common/c_cpp/src/c/list.c, though so far we don't have a reliable recreation
of the issue.

From the analysis provided:

```c
>  std::unique_ptr<Wombat::MamaTransport> tport_;
>
>  if (bridge_)  // NB. bridge_ is a mamaBridge* pointer
>  try
>  {
>     tport_.reset(new Wombat::MamaTransport);  // <-- the MamaTransport::MamaTransport constructor is successful
>     tport_->setTransportCallback(this);
>     tport_->create(tport_name, *bridge_);  // <-- this MamaTransport::create call fails and throws a MAMA exception
>   }
>   catch (const Wombat::MamaStatus& exc)
>   {
>     tport_.reset(nullptr);  //  <-- this calls MamaTransport::~MamaTransport, which triggers an unexpected crash in MAMA
>      //...
>     return false;
>   }
>   catch (...)
>   {
>     tport_.reset(nullptr);
>      //...
>     return false;
>   }
```
Reviewing the code within mama/c_cpp/src/c/transport.c, the following scenario
seems very likely:

(1) mamaTransport_create fails at some point before the call to function init

(2) self->mListeners is a null pointer (because, although
mamaTransport_allocate was successful, mListeners is assigned a list created by
list_create(sizeof (SubscriptionInfo)) in function init, which wasn't called -
see 1)

(3) mamaTransport_destroy(mamaTransport transport) is then called from the
MamaTransport::~MamaTransport destructor

(3.1) mamaTransport_destroy calls
self->mBridgeImpl->bridgeMamaTransportIsValid, which calls into the MAMA
middleware bridge and checks that the transport is valid
(3.2) the MAMA middleware bridge reports that the transport is valid
(3.3) then mamaTransport_destroy proceeds with a call to
mamaTransportImpl_clearTransportWithListeners(self)

(3.3.1) in mamaTransportImpl_clearTransportWithListeners, mRefreshTransport
is a null pointer (the initialization of mRefreshTransport would happen, if at
all, in mamaTransport_create at some point after function init is called, but
mamaTransport_create failed before the call to function init)
(3.3.2) mamaTransportImpl_clearTransportWithListeners then calls

```c
> list_for_each(impl->mListeners,
> mamaTransportImpl_clearTransportCallback, NULL);
```

which causes a crash because mListeners is a null pointer (see 2).

**Comment by MattMulhern** [comment]
Suggested fix:

```diff
diff --git a/mama/c_cpp/src/c/transport.c b/mama/c_cpp/src/c/transport.c
index 339dbc0..2eb3500 100644
--- a/mama/c_cpp/src/c/transport.c
+++ b/mama/c_cpp/src/c/transport.c
@@ -619,6 +619,9 @@
      const char*     throttleInt  =   NULL;
     if (!transport) return MAMA_STATUS_NULL_ARG;
     if (!bridgeImpl) return MAMA_STATUS_NO_BRIDGE_IMPL;
+
+    self->mListeners = NULL;
+
     mama_log(MAMA_LOG_LEVEL_FINER, "Entering mamaTransport_create for
transport (%p) with name %s", transport, name);
 
     self->mBridgeImpl = (mamaBridgeImpl*)bridgeImpl;
@@ -2626,7 +2629,10 @@
     /* Otherwise iterate the local list of subscriptions. */
     else
     {
-        list_for_each (impl->mListeners,
mamaTransportImpl_clearTransportCallback, NULL);
+     if (impl->mListeners != NULL)
+     {
+         list_for_each (impl->mListeners,
mamaTransportImpl_clearTransportCallback, NULL);
+     }
     }
 }

```

**Comment by fquinner** [comment]
#203
