### ISSUE TITLE
Proposed patch to fix invalid MAMA date logging observed on non x86 deployment

### ISSUE THREAD

**Issue by MattMulhern** [OpenMAMA/OpenMAMA#21]
**Replacing [bz-194](http://bugs.openmama.org/show_bug.cgi?id=194)**

Proposing a patch to fix an issue observed on non x86 platforms where invalid dates are logged.
The current implementation employs a time structure (struct tm) but only uses the tm_sec field. When passing to a function used to convert to local time a cast is performed. This cast causes an issue when tested on IBM Power, as a result an invalid date string was being logged to screen.

The attached patch (to be applied to mama/c_cpp/src/c/log.c) avoids the cast, using a time_t to store seconds since epoch instead of the struct and has been tested to work on both x86 and Power.

**Comment by MattMulhern** [comment]
**original patch (log.c)**
```diff
150c150
<         struct tm timeIn;
---
>         time_t timeIn = 0;
152,154c152,153
<         memset(&timeIn, 0, sizeof(timeIn));        
<         timeIn.tm_sec = timeNow.tv_sec;
<         localtime_r ((const time_t*)&timeIn, &localTime);
---
>         timeIn = timeNow.tv_sec;
>         localtime_r (&timeIn, &localTime);
```

**Comment by fquinner** [comment]
Now tracked in pull request #121.
