### ISSUE TITLE
Capturereplay should have an optional symbol file option

### ISSUE THREAD

**Issue by fquinner** [OpenMAMA/OpenMAMA#229]
Capturereplay should have a symbol file option. Symbols listed in this file will return a blank initial on first subscription until the data ticks rather than timing out. When this is specified, the initial "let's parse the entire playback file to find valid symbols" step should be bypassed.

**Comment by dmagOM** [comment]
Yeah, makes sense and should be easily enough done. I'll try and get a PR across.

**Comment by fquinner** [comment]
Implemented in #254
