### ISSUE TITLE
Move build system for OpenMAMA to cmake

### ISSUE THREAD

**Issue by fquinner** [OpenMAMA/OpenMAMA#235]
As per the email thread here:

https://lists.openmama.org/pipermail/openmama-dev/2016/001891.html

Most members of the OpenMAMA developer community would prefer to move our build system to cmake so opening this ticket to track the effort.

**Comment by Ales999** [comment]
And add please support build for mac apple

**Comment by vitya-maleyev** [comment]
I made some changes in my personal fork: mama and mamda are built with cmake on Linux only. if someone could make a branch in OpenMAMA repo, I could merge changes in to share them with others.

**Comment by fquinner** [comment]
Hi Victor - sounds good I look forward to seeing it!

You don't actually need to have write access to our main repository's
branch - you can raise a pull request right from your own fork's
development branch! Once that is approved, it then gets merged to
OpenMAMA's `next` branch.

If you have Linux covered, I'd be happy to look at windows - it would be a
good start at least!

**Comment by fquinner** [comment]
@vitya-maleyev I have pulled across your changes which look to be on your master branch into a feature branch on my fork: https://github.com/fquinner/OpenMAMA/tree/feature-cmake-support

There are a few things that may need to change around the filenames generated so we don't break target build systems and I think we should use the newly added gradle scripts for the java compilation and i'd like to look a little closer but so far so good!

**Comment by vitya-maleyev** [comment]
@fquinner
thanks, Frank! I'm going to fix scons issues and commit to my master so you'll be able to pick up the fix.

**Comment by vitya-maleyev** [comment]
@fquinner I've fixed the build. as for gradle - I'll check how to integrate it to cmake.

**Comment by fquinner** [comment]
@vitya-maleyev Yeah I added gradle (though i'm not 100% happy with it but its a start) and started porting across the qpid bridge. Then comes windows along with all the example and test apps which shouldn't be too bad there are just a *lot* of them. If you're happy enough looking at example apps, I can concentrate on windows maybe? If the scons build is fixed though I think we can start thinking about getting this into the `next` branch reasonably soon since as long as it doesn't break scons, the two can live side by side for a while.

**Comment by vitya-maleyev** [comment]
@fquinner ok, will take care of examples because unfortunately I don't have Windows setup.

**Comment by fquinner** [comment]
@Ales999 just got it building with cmake on OSX at last :)

**Comment by fquinner** [comment]
Succeeded by #361
