### ISSUE TITLE
 Infinite loop in common timers due to full socketpair

### ISSUE THREAD

**Issue by fquinner** [OpenMAMA/OpenMAMA#26]
From Duane's bugzilla ticket:

Created attachment 218 [details]
Don't require write to socketpair to succeed if the socket is full.

This issue was originally raised on the developer mailing list, and the
suggestion was to raise a bug for this.  Below I've cut 'n' pasted the
description from the original email.  I've also submitted a patch as an
attachment.

From email:

I’ve been running the timer unit tests repeatedly for over a week with the
patch submitted in bug 220:
http://bugs.openmama.org/show_bug.cgi?id=220

MamaTimerTestCPP.ForTimer recently entered a busy loop + deadlock.  After
debugging the problem, I don’t think the problem I’m seeing is specific to the
patched OpenMAMA.  I’d like to open a quick discussion to see if my proposed
fix sounds reasonable.

I saw that the socket write in _addTimer (a new function in the patch, but the
same logic as the wwrite in the original OpenMAMA) was failing due to ‘EAGAIN’,
so _addTimer entered a busy loop continually trying to write to the socket that
was full.  The reader is unable to read from the socket since the lock is being
held for the duration of the write, and the reader tries to take the lock
before reading.  By calling ioctl(heapImpl->mSockPair[0], FIONREAD, buf), I
determined there were 423 bytes available for reading.  It seems this is the
maximum number of records that can be written to a socket pair in Linux.  See:
http://stackoverflow.com/questions/10899814/af-unix-socket-overhead

I’m thinking that to fix this, we can simply ignore EAGAIN (and for maximum
portability EWOULDBLOCK as well).  If the socket is full, there are plenty of
records there to wake up the reader, so it isn’t necessary to add another
‘wake-up’ record.  Since the lock was taken before the new timer was added and
continues to be held through the write, we can just release the lock knowing
the reader has something to wake it up.

**Comment by fquinner** [comment]
Patch: https://gist.github.com/fquinner/d605c43664c13d37aeed

**Comment by dpauls** [comment]
I generated a pull request which introduces a couple of improvements to the patch posted by Frank Quinn earlier.  I described the changes in a comment within the pull request itself.

**Comment by MattMulhern** [comment]
#29  merged into next, closing off issue.

**Comment by MattMulhern** [comment]
note: adding duplicate flag to issue as pull request was actually merged.
