### ISSUE TITLE
NameError: name 'generate_source_tarball' is not defined:

### ISSUE THREAD

**Issue by btorpey** [OpenMAMA/OpenMAMA#260]
# scons .. package=yes fails
## Summary
Building 6.2.0 with package=yes fails:

NameError: name 'generate_source_tarball' is not defined:
  File "/shared/openmama-6.2.0/SConstruct", line 132:
    env.Command( '$prefix/openmama.tgz', [], generate_source_tarball )

## Areas Affected
- [ ] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [x] SCons
- [ ] Unit Tests
- [ ] Examples

## Details

Full command line:

scons product=mama with_unittest=n debug=y prefix=/build/share/openmama/6.2.0 middleware=qpid package=yes

This on CentOS 6.8

**Comment by fquinner** [comment]
Interesting - I never even noticed that parameter existed! Honestly I'll probably prune it out since github creates source tarballs and zip files automatically for us now.

**Comment by fquinner** [comment]
Succeeded by #273
