### ISSUE TITLE
qpid build does not install qpid bridge libs

### ISSUE THREAD

**Issue by btorpey** [OpenMAMA/OpenMAMA#261]
# qpid build does not install qpid bridge libs
## Summary
When building for qpid, qpid bridge libraries are not installed

## Areas Affected
- [ ] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [x] SCons
- [ ] Unit Tests
- [ ] Examples

## Details
Here's the command line:

    scons product=mama with_unittest=n debug=y prefix=/build/share/openmama/6.2.0 middleware=qpid

Following the build:

```
$ ls -l /build/share/openmama/6.2.0/lib
total 13216
-rw-rw-r-- 1 btorpey UNIX_sweng 3401666 Apr  3 12:52 libmama.a
-rw-rw-r-- 1 btorpey UNIX_sweng 5468222 Apr  3 12:53 libmamacpp.a
-rwxrwxr-x 1 btorpey UNIX_sweng 2600910 Apr  3 12:53 libmamacpp.so
-rwxrwxr-x 1 btorpey UNIX_sweng 1626034 Apr  3 12:52 libmama.so
-rw-rw-r-- 1 btorpey UNIX_sweng  426570 Apr  3 12:52 libwombatcommon.a
```

I'm not familiar with scons, so this may be a lack of understanding on my part, but I've been all through the docs and can't find any mention of how to accomplish this.

TIA!

**Comment by btorpey** [comment]
[scons.log.txt](https://github.com/OpenMAMA/OpenMAMA/files/890787/scons.log.txt)

**Comment by btorpey** [comment]
scons install

is necessary to actually install files (mostly -- although some files are installed even without that step).

+1 for cmake, btw

**Comment by fquinner** [comment]
Thanks for reporting (even though you resolved it yourself). I don't know if this interests you or not but we provide rpm and source rpm builds for both stable and snapshot versions of OpenMAMA now. And yes I'll be a lot happier once we are on cmake!
