### ISSUE TITLE
SEGV in qpidBridgeMamaTransportImpl_dispatchThread when subCount > 1

### ISSUE THREAD

**Issue by btorpey** [OpenMAMA/OpenMAMA#262]
# SEGV in qpidBridgeMamaTransportImpl_dispatchThread when subCount > 1
## Summary
pn_data_copy called with dest == NULL

## Areas Affected
- [x] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [ ] SCons
- [ ] Unit Tests
- [ ] Examples

## Details
Curious if I'm doing something wrong here, but it *appears* that if an incoming message is destined for multiple subscribers, it will always crash.

As you can see from the attached, pn_data_copy is being called with tmpMsg_node->mMsg, but since tmpMsg_node->mMsg is NULL, the code eventually SEGV's in pni_data_current.

**Comment by btorpey** [comment]
![screen shot 2017-04-04 at 4 04 57 pm](https://cloud.githubusercontent.com/assets/6627450/24676845/9dba3a8c-1952-11e7-9f45-f8e5560efa74.png)

**Comment by fquinner** [comment]
Hmm the node member is supposed to get created on memory pool initialization - this happen at low rates or is queuing likely?

**Comment by btorpey** [comment]
Very low rates -- this is just a simple "loopback" test that is both a publisher and a subscriber, and checks that it receives the messages that it sends.

What it does that may be unusual is that it creates two subscriptions for the same topic.  

When I comment out the second subscription, it all appears to work fine.

**Comment by btorpey** [comment]
BTW, the *node* structure gets allocated (and zero-initialized) just fine, but the mMsg member is NULL, which is the cause of the crash in pn_data_copy().

**Comment by fquinner** [comment]
Yeah I saw that, its supposed to get initialized for every member in `qpidBridgeMamaTransportImpl_msgNodeInit`. I'll get a proper look when I get to a machine but rest assured your application *should* have been able to subscribe to the same topic with two subscriptions fine so this looks like a qpid bridge bug.

**Comment by fquinner** [comment]
This what I had a suspicion of which is why i was was asking about the queue -
 we don't initialize newly allocated pn_message where the pool is empty and a fresh node is allocated: https://github.com/OpenMAMA/OpenMAMA/blob/master/common/c_cpp/src/c/mempool.c#L123

The default pool size is 128, you can increase it with `mama.qpid.transport.<transportname>.msg_pool_size` (if that's even the problem)

**Comment by fquinner** [comment]
Pull request raised to address this #263

**Comment by btorpey** [comment]
Thanks!  That seems to resolve the problem.

**Comment by fquinner** [comment]
Thanks @btorpey - #263 now merged into next - closing out.
