### ISSUE TITLE
Benchmark code and/or results?

### ISSUE THREAD

**Issue by btorpey** [OpenMAMA/OpenMAMA#265]
# Benchmark code and/or results?
## Summary
Does anyone have benchmark code and/or results for OpenMama w/various transports?

## Areas Affected
- [x] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [ ] SCons
- [ ] Unit Tests
- [ ] Examples

## Details
I've looked around on the wiki and the mailing list, as well as official docs, as well as Google'd, and can find no trace of any benchmarks.

I'd be most interested in code that I can run myself, but failing that, any results that others have managed to produce would be welcome.

I do see some code in the source directory, but instructions on how to run such are pretty much non-existent.

Thanks in advance!

**Comment by fquinner** [comment]
We don't really have any independent OpenMAMA hardware on which to benchmark different middlewares, and a lot of middlewares are closed source so we don't have access to test them, but I can certainly say (with a caveat that I'm expected to be biased) that ZeroMQ is significantly faster than qpid (see http://fquinner.github.io/2015/09/13/so-it-begins/), and you can expect commercial middlewares to be faster again. I'll treat this ticket as an action to generate some documentation on how to performance test bridges though because you're not the first to mention it. It's basically using mamaproducerc_v2 and mamaconsumerc_v2 with a ramp test, then checking to see when latency starts to deteriorate or else the received rate is below the expected rate.

**Comment by fquinner** [comment]
Basic commands to get you started until documentation is up to scratch:

On the publish side:

    taskset -c 1 ./mamaproducerc_v2 -numTopics 10000 -rt -tport pub -m qpid -target 100000 -steps 5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100 -stepInterval 10

On the receive side:

    taskset -c 2 ./mamaconsumerc_v2 -tport sub -m qpid -genSyms 10000 -csv report.csv

So it uses taskset to bind process for a single core (whether or not you should do this may vary according to middleware), then publishes up to a maximum rate of 100k msg/s at 5% intervals which are 10 seconds apart. It also does so with 10k symbols (always test with lots of symbols - it ensures that you include any hashing involved in the results). Stats are logged to screen and to .csv file. You can also add `-percentiles 50,90,99,99.9` to the producer command to generate percentiles.

Note that to build these tools, you need to add `with_testtools=y` to your build command

**Comment by btorpey** [comment]
OK, so it's taken a while, but on a dual-quad Core i7 running CentOS 6, it looks like I'm getting max rates around 40,000 msgs/second w/qpid direct (no broker), and something like 15,000 msgs/second using qpid with qpid-cpp-server as broker.  

This is using 6.2.0 release rpm (https://github.com/OpenMAMA/OpenMAMA/releases/download/OpenMAMA-6.2.0-release/openmama-6.2.0-1.el6.x86_64.rpm). 

Does that sound about right?  TIA!

**Comment by btorpey** [comment]
OK, I'm stumped.  I'm unable to get the qpip/broker configuration working at all.  I've tried different versions of openmama (rpm and built from source) -- ditto for libqpid-proton.so.  (The qpidd broker is built from source, since the version included with CentOS 6 apparently doesn't work with OpenMama -- see https://github.com/OpenMAMA/OpenMAMA/issues/268).

The producer and broker both spin up to 100% CPU, as does the consumer.  The consumer displays no output, but quickly consumes all the RAM on the machine (16GB) and starts swapping, at which point I have to kill (-9) it.

I'm getting the same results on two machines -- a newer dual-quad Brix, and an older dual-dual Dell, both running CentOS 6.8.  I'm using the mama.properties file from the 6.2.0 rpm (with "-tport broker -m qpid " for both mamaproducerc_v2 and mamaconsumerc_v2).

Any help or clues would be appreciated.  Thanks in advance ...

**Comment by btorpey** [comment]
One more thing, mamapublisherc/mamasubscriberc works as documented with the same config.

**Comment by fquinner** [comment]
Ouch, you try it at rates of 10msg/s or so just yo let updates trickle through? Producer always pins anyway so that's not too concerning but its unusual for the consumer to

**Comment by btorpey** [comment]
At lower rates (-numTopics 100 -target 1000), both producer and consumer pin at 100% cpu, broker is basically cruising.  Still no output from consumer, and it still grabs all 16GB, then starts swapping (although not as quickly).

**Comment by fquinner** [comment]
I just tried this and it seemed to work fine. One thing I did notice though is that when you compile the latest qpidd yourself, it will actually go ahead and continue without AMQP 1.0 (required for qpid proton) support. You will see this in the cmake output before it moves on with the build:

    -- Qpid proton not found, amqp 1.0 support not enabled

You might want to check your cmake output to verify qpidd is compiled with proton support. You can add it by doing `yum install qpid-proton-c-devel`.

On your rates front 40k sounds about right for qpid proton.

**Comment by btorpey** [comment]
I assume if there were a problem with qpidd then the publish/subscribe test would fail, but that test works as expected.

The 40K is direct (-tport pub/sub, not broker), correct?

**Comment by fquinner** [comment]
Yeah 40k is the direct. Did you try producer / consumer with a single topic (like publisher subscriber test)?

**Comment by btorpey** [comment]
With a single topic:
- producer is able to publish more messages (up to approx 42,000/sec), while pinning CPU @ 100%
- at above rates, qpidd is also pinned at 100% CPU
- still no output in consumer, although consumer is no longer pinning CPU

Note that I do see error messages in qpidd log:

```
2017-04-24 13:30:01 [Management] error Detected two management objects with the same identifier: 0-3-1--115892(org.apache.qpid.broker:incoming:91318317-9E77-4323-88AE-256FD02B6B07,sender-xxx)
```


FWIW, I rebuilt qpid-cpp with system version of qpid-proton (0.17.0), as you suggested [here](https://github.com/OpenMAMA/OpenMAMA/issues/268).  Build log attached.

[build.txt](https://github.com/OpenMAMA/OpenMAMA/files/952583/build.txt)

**Comment by fquinner** [comment]
You try with the old fashioned -s A? I tested with 10 topics and 50msg/s or so rates and it seemed to work OK so it should work OK. That was on a pretty underpowered VM too. I noticed the latency seems to get pretty poor with more topics though. Qpid has always been pretty slow though you should certainly be getting data. You can also modify the transport to use fewer topic channels if you modify your mama.properties transport not to go down to topic level in the URI which should speed it up a little. If you're looking for performance though you really should consider the zeromq bridge / omnm.

**Comment by btorpey** [comment]
> You try with the old fashioned -s A?
No idea how to do that.  Can you suggest command lines for producer/consumer?  It would be helpful I suppose to at least confirm that broker config is working (although publisher/subscriber test seems to indicate that it is).

If the results I'm getting are "real" then I find it hard to understand how the qpid broker config is useful in anything other than the most constrained use cases.

**Comment by fquinner** [comment]
Its pretty much the same as publisher subscriber:

    mamaproducerc_v2 -s A -rt -tport broker-m qpid -target 100
    mamaconsumerc_v2 -tport broker -m qpid

**Comment by btorpey** [comment]
Thanks for that!  At least I've got something I can run...

I'll play around with different combinations of rates and # symbols, but at first glance it looks like you're quite right about latency going south with more topics.  There definitely appears to be a cliff, and once you go beyond that, all sorts of bad things start to happen.

P.S.  The consumer also needs the `-s A` param, above.

**Comment by fquinner** [comment]
Yeah I corrected after spotting - nothing to see here ;)

To be honest we should probably review the qpid bridge but its always been a moving target. They have changed their interface many times. I noticed during the last release that pn_messenger which was the core API when we wrote this bridge now even has deprecation flags on it so we will need to revisit soon anyway. They have a "proactor" API now which does look cleaner. *might* help its performance vs. pn_messenger API which was always horribly synchronous and slow hopefully this one is an improvement. The payload itself though will throttle you to around 90k msg/s (or at least it did when I tested using qpid payload over zmq some time ago).

**Comment by btorpey** [comment]
OK, here's some Q&D results -- curious if these look reasonable to you:

| Rate   | Topics | Max Publish Rate (approx) | Max Receive Rate (approx) | Bottleneck | Notes          | 
|--------|--------|---------------------------|---------------------------|------------|----------------| 
| 1,000  | 10,000 | 400                       | 0                         |            | consumer hangs | 
| 100    | 10,000 | 100                       | 0                         |            | consumer hangs | 
| 10,000 | 100    | 10,000                    | 10,000                    |            |                | 
| 10,000 | 1,000  | 5,900                     | 5,500                     | qpidd      |                | 

From this I would conclude that the qpid/broker configuration is seriously challenged when the number of topics gets up around 1K, and completely borked at 10K topics.

**Comment by fquinner** [comment]
"Reasonable" is a bit of a stretch but it does seem to match the results I'm seeing here...

The moving part here is the number of URIs which the broker and messengers are managing here. You can change the URI to use just the MAMA Source which should significantly improve performance:

    mama.qpid.transport.broker.outgoing_url=topic://127.0.0.1/MAMA/%r/%S
    mama.qpid.transport.broker.incoming_url=topic://127.0.0.1/MAMA/%r/%S

The reason I didn't do this by default was because i never liked the idea of depending on client-side filtering when that feels like the broker's job, but when topic count goes up, it looks like it's the only feasible option.

**Comment by fquinner** [comment]
Hi @btorpey - just created https://openmama.github.io/openmama_performance_testing.html to track some of these commands and general words of advise around performance testing. Note that you're welcome to edit that page yourself as well - it turns into a pull request it you want to add anything which you have learned during your experiments.

**Comment by btorpey** [comment]
Wow -- nicely done, and thanks for that!
