### ISSUE TITLE
required qpidd version?

### ISSUE THREAD

**Issue by btorpey** [OpenMAMA/OpenMAMA#268]
# required qpidd version?
## Summary
What is minimum required version of qpidd?  

## Areas Affected
- [x] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [ ] SCons
- [ ] Unit Tests
- [x] Examples

## Details
On CentOS 6, the version of qpid-cppserver is 0.14, and does not accept the --topic-patterns parameter:

```
$ qpidd --auth no --topic-patterns 'MAMA.*' 
2017-04-20 11:31:26 debug Exception constructed: Error in command line options: unknown option topic-patterns
Use --help to see valid options
$ qpidd --version
qpidd (qpidc) version 0.14
```

Is there a different command line that can be used to run samples with system-provided qpidd?

Or is it necessary to build qpidd from source?  

TIA!

**Comment by fquinner** [comment]
Good question - it definitely existed when i originally submitted it:

https://lists.openmama.org/pipermail/openmama-dev/2014-September/001350.html

Strange that it's so far behind on centos 6 when qpid proton is actually fairly recent.

**Comment by btorpey** [comment]
qpidd exists, but is apparently too old (0.14), and does not accept --topic-patterns param (see above).  So I built 0.17.0 from source, which appears to work, but as mentioned elsewhere at least some of the samples don't work as documented (https://github.com/OpenMAMA/OpenMAMA/issues/265).

What OS were you using for the patch?  What OS is Jenkins CI running on?  Is that the only OS that is tested?

**Comment by fquinner** [comment]
I compiled http://qpid.apache.org/releases/qpid-cpp-1.36.0/ on a new, clean CentOS 6.9 install which had qpid proton 0.17.0 devel package from yum running.

**Comment by btorpey** [comment]
OK -- thanks.

It could be helpful to know specifically what versions used for builds and tests.

**Comment by fquinner** [comment]
We use whatever is latest on EPEL repo at the time of release - unfortunately it changes pretty regularly including their interface since qpid proton is pretty volatile.

**Comment by btorpey** [comment]
That's fine (I guess), but is that documented anywhere?  Things like compiler version, OS version, etc. can be very helpful, esp. for those (like me) who are attempting to repro the versions used.

**Comment by fquinner** [comment]
You shouldn't have to repro using the exact same versions we tested with. In fact I would discourage it since they're usually out of date and no longer supported versions. You always should recreate on the latest, stable, supported version of third party libraries otherwise when you report bugs to third parties, the first thing they ask you to do is to recreate on recent versions anyway.
