### ISSUE TITLE
MamdaSubscription redundantly creates Exception instance in onMsg

### ISSUE THREAD

**Issue by clumsy** [OpenMAMA/OpenMAMA#269]
# MamdaSubscription redundantly creates Exception instance in onMsg
## Summary
onMsg is a rather hot method in MamdaSubscription. For some reason new Exception instance is being created even if there's no error to be handled.
This not only creates garbage, but also pollutes the profilers that track Exception creation (e.g. JMC, YourKit)

## Areas Affected
- [ ] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [x] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [ ] SCons
- [ ] Unit Tests
- [ ] Examples

## Details
The Exception instance should only be created when an error is handled.

**Comment by fquinner** [comment]
Yup fully in agreement, you going to turn that commit into a pull request?

**Comment by clumsy** [comment]
@fquinner It's already submitted: #270

**Comment by fquinner** [comment]
My bad - completely missed that notification for some reason, closing this off and tracking through #270
