### ISSUE TITLE
Date/Time Range Limitation in 32-bit Linux

### ISSUE THREAD

**Issue by dpauls** [OpenMAMA/OpenMAMA#275]
# Date/Time Range Limitation in 32-bit Linux
## Summary
My apologies if this is already tracked, but I don't see anything in the open issues.  32-bit Linux only supports the standard 32-bit time_t range.  This is due to OpenMAMA's use of `time_t` in `mama_datetime_t`.

## Areas Affected
- [X] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [ ] SCons
- [ ] Unit Tests
- [ ] Examples

## Details
OpenMAMA 6.2.0 introduced an extended range of date/time objects.  However, the internal mama date/time structure `mama_datetime_t` uses a `time_t` to represent the date/time.  In 32-bit Linux, this is a 32-bit value, so the supported OpenMAMA date/time range is not extended in 6.2.0.

**Comment by glennmcclements** [comment]
32 bit Linux is no longer actively supported in OpenMAMA. This was a pragmatic decision after we reached out to users and no one was actually using it anymore, unlike 32 bit Windows.

**Comment by fquinner** [comment]
Looks like there are some legacy applications around which still use this so I have been working on getting this ported across.

It's not quite as simple as just changing the internal type of the struct member though, here are some key excerpts from related conversations:

> If we changed the internal time to be an int64 rather than a time_t, that would still pose a problem for the bridge method since it expects a timespec in the recommended getter / setter which is still restricted to time_t as a member. To support a setter / getter for that, we would need to either create some new public MAMA methods to explicitly support 64-bit signed integer timestamp values or else depend on the F64 based methods though they will have slightly less precision when you push the limits of the type.

> The public MAMA string formatting functions would also only work for smaller date range since they still depend on time_t (Apache APR uses gmtime on linux). To work around the string formatting changes, we could additionally submit changes that will figure out if the underlying date is out of range and report an error during string parsing functions rather than return gibberish. Then we should be able to update the member to be explicitly 64-bit and report an error when we know that string parsing methods would fail.

> Basically to support this, we’d be working against the OS, but it could be done (partially at least)

So that's effectively what I'm implementing at the moment.

**Comment by fquinner** [comment]
Succeeded by #277
