### ISSUE TITLE
MAMAC 6.2.1rc1 Linux 32 bit timeval and timespec returns invalid seconds value on overflow

### ISSUE THREAD

**Issue by cjwmorgan-sol-sys** [OpenMAMA/OpenMAMA#284]
# MAMAC Linux 32 bit timeval and timespec returns invalid seconds value on overflow
## Summary
The functions `mamaDateTime_getStructTimeSpec` and `mamaDateTime_getStructTimeValWithTz` return a `struct timespec` and a `struct timeval`, respectively, with invalid tv_sec when the mamaDateTime seconds value beyond the 32 bit value representation.

## Areas Affected
- [x] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [ ] SCons
- [ ] Unit Tests
- [ ] Examples

## Details
On the Linux 32 bit platform `struct timespec` and `struct timeval` have `time_t` tv_sec which is 32 bits. As a result when the functions `mamaDateTime_getStructTimeSpec` and `mamaDateTime_getStructTimeValWithTz` are used on a `mamaDateTime` value outside the 32 bit time_t range the return value is truncated yet the function return status is `MAMA_STATUS_OK`. Other function like `mamaDateTime_getAsString` seem to be able to check for this issue and return `MAMA_STATUS_INVALID_ARG`.
ie.
```
mama_status mamaDateTime_getAsString (const mamaDateTime dateTime,
                                      char*              buf,
                                      mama_size_t        bufMaxLen)
{
...
    // If time_t cannot represent the time, return error
    seconds = (time_t) mamaDateTimeImpl_getSeconds(aDateTime);
    if ((int64_t)seconds != mamaDateTimeImpl_getSeconds(aDateTime))
           return MAMA_STATUS_INVALID_ARG;
...
}
```

These functions  (`mamaDateTime_getStructTimeSpec` and `mamaDateTime_getStructTimeValWithTz`) should indicate the return value is invalid on Linux 32 bit if possible.

**Comment by garymolloy** [comment]
Hey Chris,

I'll take a look into this for you

Thanks,
Gary

**Comment by fquinner** [comment]
Yeah we'll need similar checks in the struct getters.

**Comment by fquinner** [comment]
Succeeded by #289
