### ISSUE TITLE
Unit Tests Linux 32 bit VectorDateTime comparison failures due to precision loss

### ISSUE THREAD

**Issue by cjwmorgan-sol-sys** [OpenMAMA/OpenMAMA#285]
# Unit Tests Linux 32 bit VectorDateTime comparison failures
## Summary
While running Unit tests on Linux 32bit I have been seeing failures in some of the unit tests for Vector DateTimes and they are caused when trying to compare vector DateTimes put into msgs with vector DateTimes taken back out from the same message. 

## Areas Affected
- [ ] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [ ] SCons
- [x] Unit Tests
- [ ] Examples

## Details

These are the affected tests:

```
UnitTestMamaPayloadC
[  FAILED  ] 7 tests, listed below:
[  FAILED  ] PayloadVectorDateTimeTests.AddVectorDateTime
[  FAILED  ] PayloadVectorDateTimeTests.UpdateVectorDateTime
[  FAILED  ] PayloadVectorDateTimeTests.UpdateVectorDateTimeNullUpdate
[  FAILED  ] PayloadVectorDateTimeTests.UpdateVectorDateTimeNullMessage
[  FAILED  ] PayloadVectorDateTimeTests.GetVectorDateTime
[  FAILED  ] PayloadDateTimeTests.UpdateDateTime
[  FAILED  ] PayloadDateTimeTests.UpdateDateTimeNoAdd
UnitTestMamaMsgC
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] MsgVectorDateTimeTestsC.AddVectorDateTime
[  FAILED  ] MsgVectorDateTimeTestsC.UpdateVectorDateTime
[  FAILED  ] MsgVectorDateTimeTestsC.GetVectorDateTime
```

They fail when `mamaDateTime_equals()` returns 1 since the mNanoSeconds are not equals due to precision loss from the `mamaDateTime_getEpochTimeSeconds` and `mamaDateTime_setEpochTimeF64` used to assign value to the DateTimes in the vectors in the bridge. The functions `mamaDateTime_getEpochTimeSeconds` and `mamaDateTime_setEpochTimeF64` also don't fully support nano second access due to precision loss.

I have notice that the datetime unit tests in `datetimetest.cpp` accounted for this with a margin of error. This would indicate to me that `mamaDateTime_equals` is not as reliable as in previous releases. Since it is __possible__ to assign nano seconds for all datetimes via the `mamaDateTime_setFromStructTimeSpec` function then add seconds via the `mamaDateTime_addWholeSeconds` function but it is __not possible__ to access for all datetimes nano seconds via the `mamaDateTime_getFromStructTimeSpec` function. _(Currently in 6.2.1rc1 it is possible to access nano seconds using `mamaDateTime_getFromStructTimeSpec` but there is issue #284 which would remove this access with good reason.)_

All in all, I can see these unit test failures in two ways:

1. The margin of error (10us) in `datetimetest.cpp` would seems to indicate that the unit tests are hiding a lack of support (ie. accurate nano seconds access and assignment) for extended datetime on 32 bit Linux being shown by the failing unit tests. And new OpenMAMA API function(s) are necessary to fully support extend datetime in 32 Bit Linux perhaps around nano seconds access and modification (something like `mamaDateTime_getMicroSeconds` and `mamaDateTime_addMicroSeconds` but for nano seconds) with updated unit tests without the margin for error.

2. The margin of error in `datetimetest.cpp` needs to be applied to all unit tests comparisons of `mamaDateTime` to be fixed. And also preferably some documentation (wiki page, release note?) around how on Linux 32 bit, accurate nano seconds access is not possible to applications and Bridges.

In the end I'm not sure where this problem may be in: OpenMAMA Library Interface/Bridges, UnitTests, etc. Any thoughts?

**Comment by fquinner** [comment]
Yeah I had to resort to more fuzzy checking in the mamadatetime tests. As far as I can remember, microsecond resolution generally worked fine, but that started to get lost when you started getting into large extended values. That's more reflective of the F64's ability to store data though rather than anything else. There's nothing we can really do about that - we have to trust the value provided as being accurate.

We figured this was a sensible tradeoff at the time, since realistically if you're reporting an event from the year 4375 (as it was in the unit tests which used that method), you probably don't need subsecond precision at all so F64 should probably be fine. The timespec methods should always be preferred where possible.

We mentioned this before on #275. It would have felt wrong to add an explicit getter and setter which is only useful for 32 bit machines, so we decided to depend on F64 with caveats:
https://github.com/OpenMAMA/OpenMAMA/issues/275#issuecomment-302391038

We're going to have to depend on you to provide a fix for this though since we don't have access to a payload bridge which supports extended datetime to test with, but hopefully the above should help.

**Comment by cjwmorgan-sol-sys** [comment]
Ok, I've thought through some options and out of those options here is what I believe would be the best.

Two new functions would be added to the OpenMAMA datetime API:

1. 
``` 
mama_status mamaDateTime_getWithHintsExt(mamaDateTime dateTime, 
                                         mama_i64_t* seconds, 
                                         mama_u32_t* nanoseconds, 
                                         mamaDateTimePrecision* precision,
                                         mamaDateTimeHints* hints)
 ```
2. 
``` 
mama_status mamaDateTime_setWithHintsExt(mamaDateTime dateTime, 
                                         mama_i64_t seconds, 
                                         mama_u32_t nanoseconds, 
                                         mamaDateTimePrecision precision,
                                         mamaDateTimeHints hints)
 ```


These functions would provide uniform behaviour across all platform for applications and bridges since it is not dependent on a platform specific type like `time_t` in its parameters. The behaviour of these functions should be the same as the non "ext" counterparts except the parameters allow for the range of value that the extended datetimes can represent. 

Also, I'm not sure why these functions were not added as a part of the initial extended datetime format feature. Is there a reason why these function were not added initially?

**Comment by fquinner** [comment]
I would actually suggest something a little more slim if you really want to go down this route (I never liked the combining of meta data with core data):

    mama_status mamaDateTime_setEpochTimeExt(mamaDateTime           dateTime,
                                             mama_i64_t             seconds,
                                             mama_u32_t             nanoseconds);

    mama_status mamaDateTime_getEpochTimeExt(mamaDateTime           dateTime,
                                             mama_i64_t*            seconds,
                                             mama_u32_t*            nanoseconds);

And I'll put other suggested prototypes on hints / precision on #286 for precision / hints.

As I mentioned earlier we preferred the F64 approach for extended values for pragmatic reasons:

* It would effectively a prototype which is only required for 32-bit linux which very few people run and I expect will eventually disappear for most use cases
* If you're dealing with values which time_t can't handle, you probably don't care about sub-second resolution
* The interface is already way more bloated than I would like, so I don't like adding new methods unless absolutely necessary

**Comment by fquinner** [comment]
Succeeded by #287
