### ISSUE TITLE
MAMAC Cannot access mamaDateTime Precision and Hints fields with extends values.

### ISSUE THREAD

**Issue by cjwmorgan-sol-sys** [OpenMAMA/OpenMAMA#286]
# MAMAC Cannot access mamaDateTime Precision and Hints fields with extends values.
## Summary
When a `mamaDateTime` has a seconds value greater than `UINT32MAX` the functions to access the hints and precision values, ie. `mamaDateTime_getWithsHints`, return MAMA_STATUS_INVALID.

## Areas Affected
- [x] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [ ] SCons
- [ ] Unit Tests
- [ ] Examples

## Details
As a work around for OpenMAMA 6.2.0 my bridge used the `mamaDateTimeImpl_getPrecision` and `mamaDateTimeImpl_getHints`. I now think after the problem in issue #281 that this work around should not be used. Unfortunately, the functions to access these fields also take a `seconds` parameter which would return an error for extended datetime values. 

I would need at least bridge public accessors, although I don't see why they could not be public APIs,  for precision and hints, eg. `mamaDateTime_getPrecision(const mamaDateTime dt, mamaDateTimePrecision* result)` and `mamaDateTime_getHints(const mamaDateTime dt, mamaDateTimeHints* result)`.

**Comment by fquinner** [comment]
They should definitely have public accessors. In fact they always should have been even before these changes.

**Comment by fquinner** [comment]
As discussed on #285, I think these should be fairly granular getters and setters, something like:

    mama_status mamaDateTime_getHints(mamaDateTime       dateTime,
                                      mamaDateTimeHints* hints);

    mama_status mamaDateTime_setHints(mamaDateTime       dateTime,
                                      mamaDateTimeHints  hints);

    mama_status mamaDateTime_getPrecision(mamaDateTime           dateTime,
                                          mamaDateTimePrecision* precision);

    mama_status mamaDateTime_setPrecision(mamaDateTime           dateTime,
                                          mamaDateTimePrecision  precision);

**Comment by cjwmorgan-sol-sys** [comment]
I believe there is already a `mamaDateTime_setPrecision` which I already use in my bridge. The other three:
```
mama_status mamaDateTime_getHints(mamaDateTime       dateTime,
                                  mamaDateTimeHints* hints);

mama_status mamaDateTime_setHints(mamaDateTime       dateTime,
                                  mamaDateTimeHints  hints);

mama_status mamaDateTime_getPrecision(mamaDateTime           dateTime,
                                      mamaDateTimePrecision* precision);

```

Look fine to me :)

**Comment by fquinner** [comment]
Succeeded by #287
