### ISSUE TITLE
MamdaOrderBookField Price Level Time is not set when given a book time 1970-01-01 00:00:00 (seconds=0)

### ISSUE THREAD

**Issue by cjwmorgan-sol-sys** [OpenMAMA/OpenMAMA#295]
# MamdaOrderBookField Price Level Time is not set when given a book time 1970-01-01 00:00:00 (seconds=0)
## Summary
When populating a `MamaMsg` from a `MamdaOrderBook` using `populateDelta` member the field Price Level Time is not added to the `MamaMsg` when the Price Level Time value is 1970-01-01 00:00:00 (mama_datetime_t = {secs=0, nsec=0, precision=MAMA_DATE_TIME_PREC_SECONDS, hints=0x03}).

## Areas Affected
- [ ] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [x] MAMDA
- [x] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [ ] SCons
- [ ] Unit Tests
- [ ] Examples

## Details
When adding a book level during `populateDelta`  in the method `Wombat::MamdaOrderBookWriter::MamdaOrderBookWriterImpl::addBookLevel` the price level time is compared to the delta book time (from delta.getEventTime) and if these are not equal the Price Level Time value is added to the `MamaMsg` being populated. The issue I found is how the MamaDateTimes from the delta event time and the Price Level time using only mamaDateTime compare only checks for a difference in seconds and nanoseconds so for the mamaDateTime values Empty (mama_datetime_t = {secs=0, nsec=0, precision=MAMA_DATE_TIME_PREC_SECONDS, hints=0x00}) and 1970-01-01 00:00:00 (mama_datetime_t = {secs=0, nsec=0, precision=MAMA_DATE_TIME_PREC_SECONDS, hints=0x03}), mamaDateTime_compare returns 0 when they are actually different.

I think quick and easy fix for this is to add a check for empty mamadatetimes to the check for adding Price Level Time in `MamdaOrderBookWriterImpl::addBookLevel`.
Here is what it is currently (MamdaOrderBookWriter.cpp:489) :
```
if ((NULL == bookTime || (bookTime->compare (level->getTime())!=0)))
{
    msg.addDateTime (NULL, MamdaOrderBookFields::PL_TIME->getFid(),
                     level->getTime());
}
```

Here is what the fix would like:

```
if ( (NULL == bookTime || (bookTime->compare (level->getTime())!=0))
                || bookTime->empty() != level->getTime().empty() )
{
       msg.addDateTime (NULL, MamdaOrderBookFields::PL_TIME->getFid(),
                       level->getTime());
}
```
This should target the case when comparing an Empty mamaDateTime to 1970-01-01 00:00:00 mamaDateTime. I have tested that changes address the issue

I not too familiar with the mamda APIs and their usage so not too sure if this would affect anything else. I would think this change would be pretty safe though. I would like to raise a pull request with these changes if there is no obvious impact or concerns adding these changes.

**Comment by fquinner** [comment]
Yup - that change makes sense to me - you can go ahead and raise a PR
