### ISSUE TITLE
Exception thrown in the destructor

### ISSUE THREAD

**Issue by svtesan** [OpenMAMA/OpenMAMA#34]
MamaTransport::~MamaTransport (void)
     {
         if (mPimpl)
         {
    if ( mamaInternal_getCatchCallbackExceptions() && mPimpl->mCallback)
     {
     delete mPimpl->mCallback;
     }
             if (mPimpl->mDeleteCTransport)
             {
                 =>mamaTry (mamaTransport_destroy (mTransport)); <=
             }
             delete mPimpl;
             mPimpl = NULL;
         }
     }

We should just log and not throw an exception.

**Comment by fquinner** [comment]
Duplicate of #83
