### ISSUE TITLE
Incorrect prototype for bridge_getDefaultPayloadId 

### ISSUE THREAD

**Issue by svtesan** [OpenMAMA/OpenMAMA#35]
xxxxBridge_getDefaultPayloadId (char ***name, char **id)
 The function retrieves the payload id which are const and hence params must be const qualified 
-> (const char ***name, const char **id).

**Comment by fquinner** [comment]
Only const in avis which is getting retired on Monday if there are no further objections

https://github.com/OpenMAMA/OpenMAMA/blob/master/mama/c_cpp/src/c/bridge/avis/bridge.c#L59

vs

https://github.com/OpenMAMA/OpenMAMA/blob/master/mama/c_cpp/src/c/bridge/qpid/bridge.c#L42
And it would involve a bridge interface change which I would rather avoid anyway unless I had to take action so closing this off.
