### ISSUE TITLE
Incorrect prototype for msgPayload_getMsg

### ISSUE THREAD

**Issue by svtesan** [OpenMAMA/OpenMAMA#36]
xxxPayload_getMsg(const msgPayload msg, const char* name, mama_fid_t fid, msgPayload* result) 

We are passing in a const msg and extracting its field. so, last arg should be const msgPayload*

**Comment by fquinner** [comment]
As much as I might like to make this change, the risk vs return is high. In MAMA, that `result` member is assigned to `mamaMsgImpl`'s `mPayload` member which is not const qualified. When you start tracing that through, it goes through the nervous system of all of mamaMsg and ends up touching many MAMA public methods too which may lead to application developers having to change their code to handle any resulting changes. With that in mind, I don't think we will address this one until it presents a problem.
