### ISSUE TITLE
Function(s) removed in 6.2.2

### ISSUE THREAD

**Issue by dpauls** [OpenMAMA/OpenMAMA#370]
# Function(s) removed in 6.2.2, breaking backwards compatibility
## Summary
At least one function, `mamaSubscription_setRecoverGaps` was removed in OpenMAMA 6.2.2, breaking the backwards compatibility promised by a third-digit release

## Areas Affected
- [X] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [ ] SCons
- [ ] Unit Tests
- [ ] Examples

## Details
In 6.2.2, it seems the functionality provided by `mamaSubscription_setRecoverGaps` has been refactored into the new pluggable DQ strategy.  It appears that in so doing, this function was removed from `mama/subscription.h`.

I'm not very familiar with the changes made for the pluggable DQ strategy, so I'm not sure if this is the only function removed.  This is the first build breakage we observed when integrating the 6.2.2 release.

**Comment by cjwmorgan-sol** [comment]
I have found, in openamma v6.2.3-rc1, that the structure mamaBridgeImpl which was previously bridge public in openmama v6.2.1 was made private as a part of the changes introduced in PR #339. The primary use of the structure is to set the default event queue of  bridge, as shown in the sample qpid bridge. The solace bridge used this structure for the same purpose. There is a replacement for this that is bridge public `mamaImpl_setDefaultEventQueue` however this is new and is not backwards compatible with v6.2.1. It is possible for a bridge to use mamaBridgeImpl structure should they reference the internal/private header, however based on what I can tell from the https://openmama.github.io/openmama_versioning.html page any changes in a future release to the mamaBridgeImpl structure should not warrant a minor version change, as it is now. But, changes to the mamaBridgeImpl struct will break any bridge using this structure.

As far as I can tell there are at least three options:

1.  A) Move the mamaBridgeImpl structure to the integration bridge.h header file and make it public to bridges again and keep the current release version 6.2.3. 
B) (optional/future)Should there be a want or need to make the structure private have a subsequent release with the minor version increment (eg. 6.3.X) where bridges can start using the new function `mamaImpl_setDefaultEventQueue`.

2. Scrap 6.2.3 and go straight to 6.3.0 (or 6.3.X).

3. Change nothing, with **strong** caveat that any change to the `mamaBridgeImpl` structure will cause a breaking change to current 6.2.X bridges even if its a private structure. This means bridges that set the default event queue can not migrate to using the only the integration headers and maintain backwards compatibility.

One of the goals for the next solace bridge release is to maintain backwards compatibility with openmama v6.2.1. So option 1. or 3. would be preferable. However, for option 3 it would be nice to get some confirmation/guarantee that the `mamaBridgeImpl` structure will not change as long as the minor version of openmama remains 2 (versions 6.2.X).

**Comment by cjwmorgan-sol** [comment]
Based on the discussion on the [gitter chat](https://gitter.im/OpenMAMA/OpenMAMA?at=5b620bfd20d248394f715d13), (around Aug 1st) option 3 is the way to go.
With the confirmation from fquinner:

> But yes I can confirm that bridge object wont change - we are forcing the encapsulation to allow us to be able to change it more freely if we choose to but because of this, yes it will not change until 6.3.x

**Comment by fquinner** [comment]
Thanks for all!
