### ISSUE TITLE
Scons no longer properly generating `install` directory

### ISSUE THREAD

**Issue by dpauls** [OpenMAMA/OpenMAMA#371]
# Scons no longer properly generating `install` directory
## Summary
Files are missing from the scons-generated `install` directory.

## Areas Affected
- [ ] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [X] SCons
- [ ] Unit Tests
- [ ] Examples

## Details
Beginning with release 6.2.2, the files located in `common/c_cpp/src/c/<os>/wombat` are not being put in the `install` directory's `include/wombat` directory.

**Comment by fquinner** [comment]
Succeeded by #372 - thanks!
