### ISSUE TITLE
Incorrect prototype for bridgeMamaPublisherSendReplyToInbox 

### ISSUE THREAD

**Issue by svtesan** [OpenMAMA/OpenMAMA#38]
bridgeMamaPublisherSendReplyToInbox => request is void* instead of mamaMsg 

typedef mama_status (*bridgeMamaPublisher_sendReplyToInbox)(publisherBridge publisher,
                                        =>void *         request, <=
                                        mamaMsg         reply);

This is needless as the request is a mamaMsg

**Comment by fquinner** [comment]
Implemented in #202
