### ISSUE TITLE
mamaMsg_freeString  hook for bridges

### ISSUE THREAD

**Issue by svtesan** [OpenMAMA/OpenMAMA#39]
Bridges are expected to allocate memory for some functions (toString, getReplyHandle etc) but there is no hook to free the memory. Since each bridge is allowed to use custom memory allocation, there should be a hook from mamaMsg_freeString back to the bridge. Also, currently mamaMsg_freeString  is a no-op

**Comment by MattMulhern** [comment]
This memory should be handled by the bridge implementation. An example of this can be seen in the [qpid bridge](https://github.com/OpenMAMA/OpenMAMA/blob/next/mama/c_cpp/src/c/payload/qpidmsg/payload.c#L645). 

`mamaMsg_freeString` is being deprecated also.
