### ISSUE TITLE
OpenMAMA Wombat Common windows port.h includes private headers files

### ISSUE THREAD

**Issue by cjwmorgan-sol** [OpenMAMA/OpenMAMA#398]
# OpenMAMA Wombat Common windows port.h includes private headers files
## Summary
The windows Wombat Common header file port.h include two private header files that are only accessible from the OpenMAMA source. The headers files are:

- **_lock.h_**, located at <om_src_dir>/common/c_cpp/src/c/windows
- **_mman.h_**, located at <om_src_dir>/common/c_cpp/src/c/windows

## Areas Affected
- [ ] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [X] Wombat Common
- [ ] Visual Studio
- [ ] SCons
- [x] CMake
- [ ] Unit Tests
- [ ] Examples

## Details
The Wombat Common windows port.h header has include statements at line 42 and 43:

> #include "windows/lock.h"
#include "windows/mman.h"

The windows folder header file are not included as a of an official openmama build when built using cmake. So on windows should a bridge include the port.h these header files are missing unless a bridge has the openmama wombat common source when compiling. 

The CMakelist.txt for the qpid bridge adds an include directory for openmama wombat common source in order to let the qpid bridge build. Last I recall the introduction of openmama integration header should allow bridges to build without needing openmama source code. Is this accurate?

I found scons allows adds the common source directory on build as well, since that used to be how bridges built before openmama integration headers.

Linux is unaffected by this as the port.h for linux does not include platform specific headers from wombat.

The lock.h type defs are just in the linux port.h instead of in a separate header file like windows. It should be possible to eliminate the header entirely, however making the lock.h public would work too. There is a caveat as there is already another Lock.h for wombat common Lock.cpp to be made public lock.h would need to be renamed to be different then the cpp lock.h since windows includes are not case sensitive. (Perhaps lockWin.h?) I think keeping port.h clean would be better.

The mman.h seems to have windows specific functions for file IO. Only two functions seem to be used in the openmama source **_mmap_** and **_munmap_**. Both functions are used by the internal fileparser.c module in wombat common. This leads me to think the windows mman.c replaces some linux system function? So perhaps the mman.h can be made private? If not the mman.h being made public would work too. (Also does not needs to be renamed.)

I have tried making the lock.h and the mman.h header be public by moving them in the <om_src_dir>/common/c_cpp/src/c/windows/wombat directory (with renaming lock.h). And this fixes the build error my bridge gets when trying to include port.h on windows. Should the headers files be made public or is there a better approach?

**Comment by fquinner** [comment]
Yeah that was an oversight those headers will need added to the cmake install so we don't break the interface. Even outside if port.h, its possible others were using those headers.

**Comment by cjwmorgan-sol** [comment]
Do you have something in mind? Or do you want a pull request?

**Comment by cjwmorgan-sol** [comment]
I have created a pull requesat that hopefully fixes the issue without renaming or moving any source files.
@fquinner please take a look when you can.

**Comment by cjwmorgan-sol** [comment]
Pull request got merged. Closing.
