### ISSUE TITLE
build errors w/master

### ISSUE THREAD

**Issue by btorpey** [OpenMAMA/OpenMAMA#402]
Hi Frank:

Just starting to get back up to date with latest OpenMAMA, and I'm getting build errors:

```
Linking C shared module libmamaqpidmsgimpl.so
/usr/bin/ld: CMakeFiles/mamaqpidmsgimpl.dir/qpidcommon.c.o: relocation R_X86_64_PC32 against undefined symbol `qpidmsgPayloadInternal_checkLengthAndIncDest' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [mama/c_cpp/src/c/payload/qpidmsg/libmamaqpidmsgimpl.so] Error 1
make[1]: *** [mama/c_cpp/src/c/payload/qpidmsg/CMakeFiles/mamaqpidmsgimpl.dir/all] Error 2
make: *** [all] Error 2
``` 

This is on CentOS 7.7, but I see the same build errors on CentOS 6.9.

I've compared my build logs against the build logs at <https://ci.appveyor.com/project/fquinner/openmama-gnbjp/branch/master> and don't see any obvious reason for build to fail, but I do see one other difference that is odd: I'm getting deprecated errors which don't appear in appveyor build:

```
[ 67%] Building C object mama/c_cpp/src/c/bridge/qpid/CMakeFiles/mamaqpidimpl.dir/publisher.c.o
/tmp/OpenMAMA/mama/c_cpp/src/c/bridge/qpid/publisher.c: In function ‘qpidBridgeMamaPublisher_send’:
/tmp/OpenMAMA/mama/c_cpp/src/c/bridge/qpid/publisher.c:347:5: warning: ‘pn_messenger_send’ is deprecated (declared at /usr/include/proton/messenger.h:721): Use the Proactor API or Qpid Proton C++ [-Wdeprecated-declarations]
     err = pn_messenger_send (impl->mTransport->mOutgoing,
     ^
```

Again, this is all pretty vanilla:

```
cd /tmp
git clone https://github.com/OpenMAMA/OpenMAMA.git
cd OpenMAMA
mkdir build
cd build
cmake ..
make
```

Any hints would be appreciated -- thanks!  Hope all's well with you.

**Comment by fquinner** [comment]
Hi Bill, you using the latest repo provided  version of qpid proton? Unfortunately I think the latest qpid proton version introduces some issues which came up around time of the last RC I'll have a closer look

**Comment by fquinner** [comment]
Related: #272

**Comment by btorpey** [comment]
HI Frank:

Thanks for the quick reply -- nice to hear from you.

The deprecated warnings do in fact appear because the default version of qpid on CentOS 7 is now 0.29 (from epel).  I uninstalled that and installed 0.28 from the rpm's, and that took care of the deprecated warnings. 

However, that didn't solve the linker error.  I poked around a bit and the following declaration looked a bit suspicious:

```
static inline void
qpidmsgPayloadInternal_checkLengthAndIncDest (mama_size_t  written, 
                                              mama_size_t* length, 
                                              char**        dest);
```

Removing the `inline` keyword from the declaration avoids the error -- as does removing the `static` keyword (and leaving `inline`), so it seems the combination triggers the error.  I've no idea why that is -- <https://en.cppreference.com/w/c/language/inline> doesn't make that clear, at least not to me.

I also have no clue why the appveyor build doesn't get the error, but as above a simple checkout and vanilla build on CentOS 7 does trigger the error.

**Comment by fquinner** [comment]
I feel like there's no good reason to static nor inline that function so i'd be inclined to just take both keywords out

**Comment by bill-torpey** [comment]
Created a PR for this -- left inline, although optimizer will prob do that anyway, can't hurt.

This builds on both CentOS 7 and Mac OS.

If you prefer we can lose the inline completely -- your call.

**Comment by bill-torpey** [comment]
just created a pr in upstream repo for this...https://github.com/OpenMAMA/OpenMAMA/pull/408

**Comment by fquinner** [comment]
Resolved in https://github.com/OpenMAMA/OpenMAMA/pull/408
