### ISSUE TITLE
installing APR

### ISSUE THREAD

**Issue by bill-torpey** [OpenMAMA/OpenMAMA#407]
# installing APR
## Summary
OpenMAMA installs libapr but gets it wrong.  Should it even be doing that?

### cmake
The cmake build installs a dead symlink:

```
[/home/btorpey]  ls -l ~/install/OpenMAMA/master/dev/lib
total 12220
lrwxrwxrwx 1 btorpey shared      17 Apr 21 16:17 libapr-1.so -> libapr-1.so.0.3.9
-rw-r--r-- 1 btorpey shared 2990800 Apr 21 16:15 libmama.a
-rwxr-xr-x 1 btorpey shared   95988 Apr 21 16:17 libmamabaseimpl.so
-rw-r--r-- 1 btorpey shared 4546744 Apr 21 16:15 libmamacpp.a
-rwxr-xr-x 1 btorpey shared 2233738 Apr 21 16:15 libmamacpp.so
-rwxr-xr-x 1 btorpey shared   17239 Apr 21 16:15 libmamaentnoop.so
-rwxr-xr-x 1 btorpey shared   77917 Apr 21 16:15 libmamaplugindqstrategy.so
-rwxr-xr-x 1 btorpey shared  115591 Apr 21 16:17 libmamaqpidimpl.so
-rwxr-xr-x 1 btorpey shared  240414 Apr 21 16:17 libmamaqpidmsgimpl.so
-rwxr-xr-x 1 btorpey shared 1451916 Apr 21 16:15 libmama.so
lrwxrwxrwx 1 btorpey shared      20 Apr 21 16:17 libqpid-proton.so -> libqpid-proton.so.11
-rw-r--r-- 1 btorpey shared  407254 Apr 21 16:15 libwombatcommon.a
-rw-r--r-- 1 btorpey shared    9246 Apr 21 16:15 libwombatcommoncpp.a
-rwxr-xr-x 1 btorpey shared   12211 Apr 21 16:15 libwombatcommoncpp.so
-rwxr-xr-x 1 btorpey shared  231596 Apr 21 16:15 libwombatcommon.so
[/home/btorpey] find ~/install/OpenMAMA/master/dev/lib -type l ! -exec test -e {} \; -print
/home/btorpey/install/OpenMAMA/master/dev/lib/libapr-1.so
/home/btorpey/install/OpenMAMA/master/dev/lib/libqpid-proton.so
[/home/btorpey]
```
(Note that the same thing happens with qpid libraries).

With the cmake build, libapr must be installed in any case, and it will be resolved from the system location (/usr/lib64).

### scons
The scons build copies all the symlinks as regular files:

```
[btorpey@bt-brix 6.2.1]$ ls -l /home/btorpey/install/OpenMAMA/6.2.1/dev/lib
total 12376
-rwxr-xr-x 1 btorpey shared  198704 Aug  8  2019 libapr-1.so
-rwxr-xr-x 1 btorpey shared  198704 Aug  8  2019 libapr-1.so.0
-rwxr-xr-x 1 btorpey shared  198704 Aug  8  2019 libapr-1.so.0.4.8
-rw-r--r-- 1 btorpey shared 3323464 Apr 23 16:33 libmama.a
-rw-r--r-- 1 btorpey shared 4512874 Apr 23 16:32 libmamacpp.a
-rwxr-xr-x 1 btorpey shared 2211536 Apr 23 16:32 libmamacpp.so
-rwxr-xr-x 1 btorpey shared   20232 Apr 23 16:33 libmamaentnoop.so
-rwxr-xr-x 1 btorpey shared   13400 Apr 23 16:33 libmamaplugintemplate.so
-rwxr-xr-x 1 btorpey shared 1506072 Apr 23 16:32 libmama.so
-rw-r--r-- 1 btorpey shared  455488 Apr 23 16:33 libwombatcommon.a
-rw-r--r-- 1 btorpey shared   15336 Apr 23 16:31 libwombatcommoncpp.a
[btorpey@bt-brix 6.2.1]$ 
```

Should OpenMAMA even be installing libapr?  

If so, how?  One solution is to install the library AND its symlinks (as symlinks) into OpenMAMA's lib directory.

Or would it make more sense to not install it and rely on its being installed as a separate dependency?

**Comment by fquinner** [comment]
I assume this is the tarball? It should be installing the dependencies yes because usually the tarball is usually dropped somewhere self-contained like /opt/openmama and the API can't be sure the API versions that will be present on the target system will match those that it was compiled with.

It should have dereferenced the symlink or taken the targets with it for the tarball though. That's what the `INSTALL_RUNTIME_DEPENDENCIES` parameter is for and it's specifically for tarball targets.

We do have releases tailored for centos 6 and centos 7 which shouldn't include the dependencies though (instead they should be pulled from the standard repositories). We also have cloudsmith repositories set up to serve these up with package managers including updates, dependencies etc.

What's your target system?

**Comment by bill-torpey** [comment]
Nothing to do with the tarball -- this is what a source build puts in the install directory.  

- In the case of cmake, the build installs a symlink (`libapr-1.so`) that points nowhere.  

- What's worse, is that the symlink is not the library that executables call for -- that is the SONAME of the target of the link, which is **`libapr-1.so.0`**:

```
$ ldd /home/btorpey/install/OpenMAMA/master/dev/lib/libmama.so
	linux-vdso.so.1 =>  (0x00007ffcb05ed000)
	libapr-1.so.0 => /lib64/libapr-1.so.0 (0x00007fe4adbb8000)
	libwombatcommon.so => not found
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe4ad99c000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fe4ad69a000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe4ad2cc000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007fe4ad0c7000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fe4ace90000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fe4acc8c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe4ae0ab000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007fe4aca89000)
```


You can see the SONAME of the shared library with the following command:

```
$ objdump -p /home/btorpey/install/OpenMAMA/master/dev/lib/libapr-1.so.0.4.8 | grep SONAME
  SONAME               libapr-1.so.0
```

I've patched our fork to install *both* symlinks, as well as the symlink target (see above commit).  That fixes the cmake build, assuming that we really do want to install our own version of libapr (which I'm not convinced is a good idea -- more on that later).

- With scons, the problem is the build copies not the symlinks, but the targets of the symlinks to the install directory.  Obviously the rpmbuild step can't fix that problem, since the symlinks have already been dereferenced before rpmbuild runs.

- As for whether we *should* install libapr, I understand the rationale, although I'm not sure I agree with it.  There are *many* dependencies that OpenMAMA does NOT install (libevent, libxml2, libuuid for starters) -- I don't understand why libapr is "special" that way.

Personally, I've come to think it's better not to bundle dependencies, but to have them taken care of by normal package management (i.e., yum on RH).  That's your call, but it would seem that if OpenMAMA is going to install *some* dependencies, it should install *all* of them, and that's a slippery slope that ends up with static linking for everything.  

FWIW, these builds are being done on CentOS 7.

**Comment by fquinner** [comment]
Try setting `-DINSTALL_RUNTIME_DEPENDENCIES=OFF` - didn't realize it was on by default. That should control that behavior. Would agree this should be non-default behavior (but it is useful for standalone installations as an option... and work properly).

**Comment by bill-torpey** [comment]
Good to know -- thanks!

But in the case where it's enabled, both cmake and scons builds are still borked.

**Comment by fquinner** [comment]
Yup I'll change default and see if I can fix that behavior under this ticket - it should not be doing that. And I'm hoping to deprecate scons entirely shortly its the source of many headaches!

**Comment by bill-torpey** [comment]
The commit above has a Q&D fix, but I'm not entirely comfortable with it, so if you can come up with a better way, that's great.  In the meantime I'll disable this behavior explicitly.

BTW, the same behavior occurs with the qpid libraries (`libqpid-proton.so` etc.), and it may make more sense to install those by default.  In any case, what gets installed today is a dead symlink.

Last but not least, so glad to hear of scons' demise -- not a moment too soon!

**Comment by bill-torpey** [comment]
Ooops - just noticed that there's a fix for this in `next` -- I have been (mistakenly) working off master.  (That is a bit confusing fwiw).

So FindAPR.cmake and FindProton.cmake do install the correct files,  but I still think there is an issue:

```
        install (FILES ${PROTON_LIBRARY_FILES} DESTINATION lib)```
```
should be

```
        install (PROGRAMS ${PROTON_LIBRARY_FILES} DESTINATION lib)
```

Otherwise the actual library file gets installed without executable bit, and so won't be considered by the loader.  (The symlinks get installed with rwx for all, so no issue there).

**Comment by bill-torpey** [comment]
Never mind -- scratch that last bit.  I was mistaken -- the loader will happily load shared libraries without the execute bit set (https://unix.stackexchange.com/questions/400187/why-should-or-should-not-shared-libraries-be-executable-e-g-red-hat-vs-debian).
