### ISSUE TITLE
Some fields are not initialized in INITIALIZE_BRIDGE 

### ISSUE THREAD

**Issue by svtesan** [OpenMAMA/OpenMAMA#41]
mamaBridgeImpl::mInternalDispatcher is not set to NULL on bridge creation which can lead to a crash if this variable is used.

**Comment by MattMulhern** [comment]
`INITIALIZE_BRIDGE` is being deprecated in favour of dynamic loading (see [dynamic loading](https://github.com/OpenMAMA/OpenMAMA/wiki/Dynamic-Bridge-Loading) changes).
