### ISSUE TITLE
Difference in behavior between mamaQueue_timedDispatch and wombatQueue_timedDispatch 

### ISSUE THREAD

**Issue by svtesan** [OpenMAMA/OpenMAMA#42]
As per comments and documentation, mamaQueue_timedDispatch is supposed to keep dispatching until the given timeout has elapsed. But, the current bridge implementations use wombatQueue_timedDispatch which dispatches only one message. So, EITHER wombatQueue_timedDispatch should be changed to keep dispatching till timeout OR another helper function should be provided to do this (as this functionality is used across bridges)

**Comment by fquinner** [comment]
I've been looking at other commercial bridges used by MAMA and their behaviour deviates too.

I don't think this is unreasonable though as the reason that we delegate queues to each implementation's bridge is to leverage methods provided by third parties and make the MAMA layer as thin as possible in the interest of performance. If you look at some of these, their behaviour varies:

* [TibRV](https://docs.tibco.com/pub/rv_zos/8.4.5/doc/html/tib_rv_cobol_reference/wwhelp/wwhimpl/common/html/wwhelp.htm#context=tib_rv_cobol_reference&file=rv_cobol_ref.6.104.htm)
* [LBM / UMS] (https://ultramessaging.github.io/UMExamples/event_q_rcv/c/event_q_rcv.sldoc.html)

Dispatch-once-with-timeout makes a lot more sense to me and is the most commonly used (I think LBM is the only exception) so I think it's a sane default, I think the documentation should simply be updated to state that this may vary depending on which implementation is used.

**Comment by fquinner** [comment]
Succeeded by #330
