### ISSUE TITLE
msgPayload_unSerialize prototype incorrect

### ISSUE THREAD

**Issue by svtesan** [OpenMAMA/OpenMAMA#43]
msgPayload_unSerialize prototype incorrect (takes in void** instead of void*) 

typedef mama_status
(*msgPayload_unSerialize)      (const msgPayload    msg,
                                =>const void**        buffer, <=
                                mama_size_t         bufferLength);

This is an input buffer and the only function using this is mamaMsg_setNewBuffer which calls the above function and passes a void* buffer as a void**

**Comment by fquinner** [comment]
Now tracked in pull request #123
