### ISSUE TITLE
Incorrect check, return value in MamaMsg::setNewBuffer 

### ISSUE THREAD

**Issue by svtesan** [OpenMAMA/OpenMAMA#44]
bool MamaMsg::setNewBuffer (
        void*        buffer,
        mama_size_t  size)
    {
        int result = 0;
// should be MAMA_STATUS_OK == ...
=>        if (MAMA_STATUS_OK != (mamaTry (mamaMsg_setNewBuffer ( <=
                            mMsg, buffer, size))))
        {
            return result;
        }
        return result != 0;
    }

Also, the return value is incorrect

**Comment by fquinner** [comment]
Resolved in 13e86797aecfb89285c1f19697087ac85269b4b5.
