### ISSUE TITLE
Macros defined in port.h interfere with third party headers

### ISSUE THREAD

**Issue by svtesan** [OpenMAMA/OpenMAMA#45]
There are some pesky macros defined in port.h (close, sleep etc) which causes problems when using other libraries (eg boost). We should be defining them as inline functions instead of using macros

**Comment by fquinner** [comment]
I'm not sure how would defining these as inline functions help when compared with a macro... surely if they're in port.h, it'll have the same effect either way?

In other similar conflicts that I have seen, it's typically resolved by ifdefs.

I'd also like some more details on how these problems manifest themselves please?

**Comment by svtesan** [comment]
The issues had to do with port.h providing macros for shutdown(), close, ERROR etc. IIRC, close was renamed to _close in one such definition and it caused endless grief, compounded as I compile under both windows and linux. Unfortunately it wasnt as simple as #undef/#ifdef fencing always - I had to juggle around headers, and create PIMPL classes to isolate mama from offended headers. I will try to prepare a test case cutting out the cruft.

**Comment by fquinner** [comment]
Hi there, just chasing up on this did you have any success generating a test case for this?

**Comment by fquinner** [comment]
Please reopen if you can provide some examples for us to work with.
