### ISSUE TITLE
Inconsistent prototypes 

### ISSUE THREAD

**Issue by svtesan** [OpenMAMA/OpenMAMA#46]
mama_status
mamaMsg_updateVectorPrice (
    mamaMsg               msg,
    const char*           fname,
    mama_fid_t            fid,
//should be const mamaPrice      priceList[]
    => const mamaPrice*      priceList[], =<
    mama_size_t           numElements);

msgPayload_getPrice, msgPayload_getDateTime should take pointer to result as last parameter
Eg:
typedef mama_status
(*msgPayload_getDateTime)      (const msgPayload    msg,
                                const char*         name,
                                mama_fid_t          fid,
//should be mamaDateTime *       result
=>                                mamaDateTime        result); <=

**Comment by MattMulhern** [comment]
duplicate of #63 and #62
