### ISSUE TITLE
Windows MamaListen (java) fails to shut down when dealing with multiple subscriptions

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#47]
Replacing [RB-117] (http://bugs.openmama.org/show_bug.cgi?id=117)

Java dump file.

When running the Java implementation of MamaListen, there is an intermittent
cores during shutdown when processing multiple (3 or more) symbols. This can be
reproduced against capturereplayc.exe using the sample data and dictionary. It
occurs when passing either multiple subscriptions (-s) or passing a symbol file
(-f), though not consistently.

> $ java com.wombat.mama.examples.MamaListen -m qpid -tport sub -S TEST -s DE000CM95AU4.EUR.XPAR -s PTBIZJYE0064.EUR.ENXL -s NL0009906148.EUR.XAMS -shutdown 60
> ...
>    wQuoteSeqNum         | 441  | I32        | 215618                                           
>    wQuoteCount          | 1034 | I32        | 1771                                             
>    wLinkId              | 2550 | I64        | 0                                                
>    wOrigMsgType         | 5001 | STRING     | 140                                              
>    MamaSendTime         | 16   | STRING     | 21:59:46.664                                     
> Subscription destroyed                                                                         
> Subscription destroyed                                                                          
> Subscription destroyed                                                                          
>                                                                                                
>  A fatal error has been detected by the Java Runtime Environment:                              
>                                                                                                
>   EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x73f255d7, pid=2316, tid=2440                 
>                                                                                                
>  JRE version: Java(TM) SE Runtime Environment (8.0_05-b13) (build 1.8.0_05-b13)                
>  Java VM: Java HotSpot(TM) Client VM (25.5-b02 mixed mode windows-x86 )                        
>  Problematic frame:                                                                            
>  C  [libmamaqpidimplmd.dll+0x55d7]  qpidBridgeMamaTransportImpl_queueCallback+0x27             
>                                                                                                
>  Failed to write core dump. Minidumps are not enabled by default on client versions of Windows 
>                                                                                                
>  An error report file with more information is saved as:                                       
>  Z:\ZenoShare\WindowsBuild\OpenMAMA-9b899e9\openmama_install_2.3.1\hs_err_pid2316.log          
>                                                                                                
>  If you would like to submit a bug report, please visit:                                       
>    http://bugreport.sun.com/bugreport/crash.jsp                                                
>  The crash happened outside the Java Virtual Machine in native code.                           
>  See problematic frame for where to report the bug.                                            
>             

The issue appears to be triggered within the Qpid Proton bridge, though more
investigation will be required to determine the root cause.

Additional Information:
- The crash does not appear when processing 2 or 1 symbols.
- The crash appears regardless what shutdown interval is passed (tested with
10, 20, and 60 second intervals).
- The crash does not seem to appear when multiple threads are used (-threads),
though I haven't determined if there's a correlation between the number of
threads and number of symbols which may cause issues.
- The crash is observed on both 2.3.0 and 2.3.1RC2.

Attached is a java dump file from the test run.

**Comment by adriennea** [comment]
[hs_err_pid2316.txt](https://github.com/OpenMAMA/OpenMAMA/files/13923/hs_err_pid2316.txt)

**Comment by fquinner** [comment]
Can't recreate, though I wonder if it was fixed by #210
