### ISSUE TITLE
MamaInboxCS Cores when run against MamaPublisherCS over QPID

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#48]
Replacing [RB-118](http://bugs.openmama.org/show_bug.cgi?id=118)

When run against MamaPublisherCS.exe, MamaInboxCS.exe throws a
AccessViolationException, and exits.

> $ MamaInboxCS.exe -m qpid -tport sub
> Starting Publisher with:
>    topic:              MAMA_INBOUND_TOPIC
>    transport:          sub
> 
> Error occurred: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
> Details:
> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>    at Wombat.Mama.NativeMethods.mama_start(IntPtr bridgeImpl)
>    at Wombat.Mama.start(MamaBridge bridgeImpl)
>    at Wombat.MamaInboxCS.Run()
>    at Wombat.EntryPoint.Main(String[] args)

Based on the logging from MamaPublisherCS, it appears that a connection is
made, and some inbox requests are sent. However, shortly these do not appear to
be received by MamaInboxCS. 

> Publishing message to MAMA_TOPIC.
> Publishing message to MAMA_TOPIC.
> Received inbound msg. Sending response
> Publishing message to inbox.
> Received inbound msg. Sending response
> Publishing message to inbox.
> Received inbound msg. Sending response
> Publishing message to inbox.

Similar errors are observed when running MamaInboxCS against mamapublisherc,
mamapublishercpp or MamaPublisherJava.

Other combinations of Publisher (C, C++, Java) with Inbox (C, C++, Java) behave
as expected.

**Comment by fquinner** [comment]
Just ran this with latest OpenMAMA and it worked fine - maybe related to recent changes around memory cleanup and preventing access violations on windows in general.
