### ISSUE TITLE
Payload and Middleware unit-tests in Visual Studio

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#50]
Replacing [RB-125] (http://bugs.openmama.org/show_bug.cgi?id=125)

Payload and Middleware unit-test are missing from Visual Studio.

**Comment by adriennea** [comment]
The attachment is a MAMA C gtest support for Visual Studio.
[0001-MAMA-C-Unit-Tests-Support-for-Visual-Studio.txt](https://github.com/OpenMAMA/OpenMAMA/files/13929/0001-MAMA-C-Unit-Tests-Support-for-Visual-Studio.txt)

**Comment by fquinner** [comment]
Patch won't apply now since we dropped the old project format but I'll get this change into the next release. The unit test code should already compile off the back of the recent scons fixes for windows, so it's just a case of updating visual studio projects.

**Comment by fquinner** [comment]
Just dropped this into next: https://github.com/OpenMAMA/OpenMAMA/commit/2d2f3c41624b2c2985c1e21caab7dd101b800291
