### ISSUE TITLE
Default search path for gtest-md 1.7.0 libraries

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#51]
Replacing [RB-126] (http://bugs.openmama.org/show_bug.cgi?id=126)

Default x64 and Win32 builds of gtest-md are in different location.
And the search path in the unit-test MainUnitTestC does not reflect that.

Proposed solution for gtest-md 1.7.0:

I suggest to add the following paths to the property sheet of the project:

GTEST_HOME is where the gtest is extracted.

In Property Pages -> Configuration Properties -> Linker -> General -> Addition
Library Directories should add:
Win32|Debug:   $(GTEST_HOME)\msvc\gtest-md\Debug
Win32|Release: $(GTEST_HOME)\msvc\gtest-md\Release
x64|Debug:     $(GTEST_HOME)\msvc\x64\Debug
x64|Release:   $(GTEST_HOME)\msvc\x64\Release

I also suggest to make sure in the Wiki for visual studio that people build the
gtest-md (or gtest) in the following specific way to avoid confusion:

Do not build with CMake. for VS use the solution in: 
   %GTEST_HOME%\msvc\gtest-md.sln

Create x64 configuration. In configuration Manager create new platform and copy
its configuration from Win32

In gtest-md Property Pages -> Configuration Properties -> C/C++ -> Code
Generation -> Runtime Library should be:
* For Debug:   Multi-threaded Debug (/MTd)
* For Release: Multi-threaded (/MT)

Build all platforms and configuration of gtest-md

**Comment by adriennea** [comment]
Also it is worth to refer to this specific question in the gtest FAQ:
https://code.google.com/p/googletest/wiki/FAQ#How_do_I_generate_64-bit_binaries_on_Windows_%28using_Visual_Studi

**Comment by adriennea** [comment]
(In reply to comment #1)

Basically, if the user follows the answer in the FAQ that is mentioned on
comment 2, the build should work flawlessly.

So ignore comment 1, but it is worth mentioning the link to FAQ in comment 2 in
the Wiki to avoid confusion.

see link:
https://code.google.com/p/googletest/wiki/FAQ#How_do_I_generate_64-bit_binaries_on_Windows_%28using_Visual_Studi


> Proposed solution for gtest-md 1.7.0:
> 
> I suggest to add the following paths to the property sheet of the project:
> 
> GTEST_HOME is where the gtest is extracted.
> 
> In Property Pages -> Configuration Properties -> Linker -> General -> Addition
> Library Directories should add:
> Win32|Debug:   $(GTEST_HOME)\msvc\gtest-md\Debug
> Win32|Release: $(GTEST_HOME)\msvc\gtest-md\Release
> x64|Debug:     $(GTEST_HOME)\msvc\x64\Debug
> x64|Release:   $(GTEST_HOME)\msvc\x64\Release
> 
> I also suggest to make sure in the Wiki for visual studio that people build the
> gtest-md (or gtest) in the following specific way to avoid confusion:
> 
> Do not build with CMake. for VS use the solution in: 
>    %GTEST_HOME%\msvc\gtest-md.sln
> 
> Create x64 configuration. In configuration Manager create new platform and copy
> its configuration from Win32
> 
> In gtest-md Property Pages -> Configuration Properties -> C/C++ -> Code
> Generation -> Runtime Library should be:
> * For Debug:   Multi-threaded Debug (/MTd)
> * For Release: Multi-threaded (/MT)
> 
> Build all platforms and configuration of gtest-md

**Comment by adriennea** [comment]
It is also worth to mention that the user should add _VARIADIC_MAX=10 to
preprocessor defines both on the gtest build and on each unit-test project. it
is essential for compatibility with vs 2012/2013 and I think also VS 2010.

**Comment by fquinner** [comment]
This has been fixed in latest VS project files.
