### ISSUE TITLE
MAMA: Update SCons to build MAMA docs as PDFs

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#52]
Replacing [RB-142] (http://bugs.openmama.org/show_bug.cgi?id=142)

At present the SCons doxygen builder does not generate the MAMA docs as PDF
files automatically. We should add this ability into Scons.

There are a number of things to watch out for:
- We will need to check for the appropriate tools being available (pdflatex)
- There can be issues generating PDF's from tex files with cross-references.

It may be possible to either create a new tool/builder ourselves, or reuse an
existing builder to get this functionality. This will require some
investigation.

**Comment by fquinner** [comment]
Doxygen stuff should remain HTML because it's interactive and easy to navigate. You'd rarely hear of anyone preferring PDF for doxygen stuff - would be a different story if this was the dev guide though, so closing this one off.
