### ISSUE TITLE
Libraries generated by SCons on Linux do not correctly set the SONAME

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#53]
Replacing [RB-150](http://bugs.openmama.org/show_bug.cgi?id=150)

The SCons build is not setting SONAME for the shared libs (this was set
correctly with the autotools build)

e.g.

> $ objdump -p ./objdir/mama/c_cpp/src/c/.libs/libmama.so |grep SONAME

doesn't give any output. SONAME is really important when packaging.

It appears correctly for 2.2.2.1:

> $ objdump -p /usr/lib/x86_64-linux-gnu/libmama.so.0 | grep SONAME
>   SONAME               libmama.so.0

**Comment by fquinner** [comment]
Succeeded by #235
