### ISSUE TITLE
Implement generic command line parsing for example applications

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#54]
Replacing [RB-152](http://bugs.openmama.org/show_bug.cgi?id=152)

The vast majority of OpenMAMA's example applications make use of the same set
of command line options. However, each also reimplements command line parsing.
This leads to errors, inconsistency, and unfortunate levels of duplication. 

We'd like to implement a generic toolset for command line parsing that can be
included in all example applications, and which will provide a standard
interface for each application. It should also allow extension to include
commands specific to an application.

Examples of common command line arguments:

-m <middleware>
-tport <transport>
-S <source>
-s <symbol>
-f <symbol file>

**Comment by fquinner** [comment]
It also means that the application is easy to compile in various development environments though without requiring additional link stages so unless a contribution is forthcoming, I'm inclined to leave as-is.
