### ISSUE TITLE
[MAMAJAVA] Possible bug with MamaSubscription.java

### ISSUE THREAD

**Issue by MattMulhern** [OpenMAMA/OpenMAMA#56]
replacing [bz-174](http://bugs.openmama.org/show_bug.cgi?id=174).

From Gary Molloy:

> I've been testing the setupSubscription and createSubscription methods found in
> MamaSubscription.java. Key difference between the two is that setupSubscription
> is used when a subscription is created but not activated yet where
> createSubscription creates and activates the subscription.
> 
> In the setupSubscription, the closure is passed into the JNI layer instead of
> saving it in the java layer like createSubscription. Without saving this
> closure in the java layer, the value doesn't seem to be passed back properly
> from the JNI layer causing issues.
> 
> Is this a typo in MamaSubscription.java or is the JNI layer supposed to pass
> the closure back to the JAVA layer once the subscription is activated?

**Comment by fquinner** [comment]
BZ ticket gone so not sure of the context so closing out.
