### ISSUE TITLE
Deprecate mamaMsg_freeString

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#59]
Replacing [RB-17] (http://bugs.openmama.org/show_bug.cgi?id=17)

At present the mamaMsg_freeString call has no implementation, and won't
actually do anything if called. It is also confusing, as it may make API users
believe they own the memory returned by mamaMsg_toString, which may ultimately
lead to further undefined behaviour if they attempt to modify or free the
buffer.

The mamaMsg documentation should be updated to reflect the fact that freeString
is no longer supported, and references to it removed from the rest of the code
base. A note should also be added to toString to make it clear that the
returned buffer is owned by the message itself, not by the user.

**Comment by fquinner** [comment]
Now tracked in PR #124
