### ISSUE TITLE
Windows bug with FreeLibrary return value

### ISSUE THREAD

**Issue by reed-jpm-alpert** [OpenMAMA/OpenMAMA#60]
On Windows closeSharedLib calls FreeLibrary, which returns non-zero on success, but closeSharedLib returns 0 on success. Just need to flip the return value from FreeLibrary. Currently this does no harm, but the plugin code prints an error when unloading a plugin. Will submit a patch for this.

**Comment by fquinner** [comment]
Thought this looked familiar - already fixed in 24370b28d4a472bd38de2ba1a56399132a044ee4.
