### ISSUE TITLE
Capture Replay should send book clear when rewinding

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#61]
Replacing [BZ-18](http://bugs.openmama.org/show_bug.cgi?id=18)

At present, capture replay doesn't send a book clear message when it rewinds the playback file. While the data will continue to flow, it will look incorrect for orderbooks. 

In order to resolve, we should send a book clear message to clients of book subscriptions whenever they rewind.

We may also want to do the same for regular subscriptions.

**Comment by fquinner** [comment]
This isn't actually required since the first message after a rewind should be an initial which should reset the snapshot state of the book anyway.
