### ISSUE TITLE
Standardize interface for MAMA Message and Field Vector Get Price Functions

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#63]
Replacing [BZ-38] (http://bugs.openmama.org/show_bug.cgi?id=38)

The interface for these methods looks inconsistent with the others and causes difficulty in propagating results upwards from the payload implementation layer. 

The current interface looks like this:

```mama_status
mamaMsg_getVectorPrice (
    const mamaMsg         msg,
    const char*           name,
    mama_fid_t            fid,
    const mamaPrice*      result,
    mama_size_t*          resultLen)
```
Whereas it should look more like this to enable the underlying interface to *write* to the result pointer provided which in this context is essentially an array of mamaPrices:

```mama_status
mamaMsg_getVectorPrice (
    const mamaMsg         msg,
    const char*           name,
    mama_fid_t            fid,
    const mamaPrice**     result,
    mama_size_t*          resultLen)
```
This would also align with all the other getVector functions, e.g.:

```mama_status
mamaMsg_getVectorF32 (
        const mamaMsg        msg,
        const char*          name,
        mama_fid_t           fid,
        const mama_f32_t**   result,
        mama_size_t*         resultLen)
```

**Comment by fquinner** [comment]
Succeeded by #163
