### ISSUE TITLE
Implement Qpidmsg Date Time and Price Vector Support

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#64]
Replacing [BZ-39] (http://bugs.openmama.org/show_bug.cgi?id=39)

Most of the implementation has been done before so this should simply be a case of cleaning up, but it wasn't completed because of [#62] (]https://github.com/OpenMAMA/OpenMAMA/issues/62) and [#63] (https://github.com/OpenMAMA/OpenMAMA/issues/63)

Theoretically it should be possible to test these before the MAMA changes are even made using the unit test framework already existing but with new functionality added to specifically handle date time / price validation.

**Comment by fquinner** [comment]
Succeeded by #163
