### ISSUE TITLE
MAMA: Cleanup publisher topic map on dqPublisherManager destroy.

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#66]
Replacing [BZ-69] (http://bugs.openmama.org/show_bug.cgi?id=69)

Cleanup publisher topic map on dqPublisherManager destroy patch

Fixed memory leak when calling dqPublisherManager_destroy() - The contents of the publisher topic map are now freed inline with the publisher map itself being destroyed.

**Comment by adriennea** [comment]
Hey Lee, 

I've been taking a look over this one, and I'm not sure it's really a memory leak. From running a few test applications, I can't see a situation where we will leave any memory lying around unless the client application hasn't cleaned up their own publishers - either via calls to mamaDQPublisherManager_destroyPublisher or mamaDQPublisherManager_removePublisher. Even if there is such an issue, I'm also not entirely sure the fix in the patch addresses the full problem - assuming a client attempts to cleanup all the publishers using a single call to mamaDQPublisherManager_destroy, the change you've attached will still leave the mamaDQPublisher's themselves, so the app will continue to leak somewhere.

Obviously, I may have missed something with this one, so if you think there's a different reason why this code leaks let me know and I'll take another look.

I suspect the main problem here is that we don't have decent documentation/example apps which reflect the expected cleanup for an application which uses the publisher manager. I'll take a look at perhaps updating mamaProxy to demonstrate this - personally I'd go for something along the lines of:

> for (int i = 0; i < numPublishers; ++i) {
>     mamaDQPublisherManager_destoryPublisher (pubManager, publishers[i].symbol);
> }
> mamaDQPublisherManager_destroy (pubManager);

or 

> for (int i = 0; i < numPublishers; ++i) {
>     mamaDQPublisherManager_removePublisher (pubManager, 
>                                             publishers[i].symbol,
>                                             &(publishers[i].publisher));
>     mamaDQPublisher_destroy (publishers[i].publisher);
> }
> mamaDQPublisherManager_destroy (pubManager);

Cheers, 

D

**Comment by adriennea** [comment]
Test application for memory leak

Simple test app to check for memory leaks. Uses preprocessor defines to determine which version of cleanup to run:

* No define uses the mamaDQPublisherManager_destroyPublisher approach.
* -DREMOVE uses the mamaDQPublisherManager_removePublisher approach.
* -DNO_CLEANUP doesn't perform any cleanup.

D

**Comment by adriennea** [comment]
[dqpubcleanup.txt](https://github.com/OpenMAMA/OpenMAMA/files/22545/dqpubcleanup.txt)
[0001-MAMA-Cleanup-publisher-topic-map-on-dqPublisherManag.txt](https://github.com/OpenMAMA/OpenMAMA/files/22546/0001-MAMA-Cleanup-publisher-topic-map-on-dqPublisherManag.txt)

**Comment by MattMulhern** [comment]
Not verified as a memory leak. Any leak here is due to application. Closing off.
