### ISSUE TITLE
Implement reserved payload and middleware enumerations

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#67]
Replacing [BZ-93] (http://bugs.openmama.org/show_bug.cgi?id=93)

While we're working on dynamic loading of bridges and payloads, there is still a requirement that certain middleware and payload enums be reserved for internal use by non-public bridges. 

We'll need to add to both enums, their respective toString functions, the various language interfaces, and to the Unit Tests.

**Comment by MattMulhern** [comment]
Going to document reserved payloads instead of keeping it in code. Closing off.
