### ISSUE TITLE
Ant build scripts and possibly others on windows do not support directories with spaces in them

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#68]
Replacing [BZ-111] (http://bugs.openmama.org/show_bug.cgi?id=111)

There are some places where you need "$(ANT_HOME)" rather than $(ANT_HOME) etc. for MSVC. There are possibly others...

**Comment by fquinner** [comment]
just checked and all references to ANT_HOME have already been placed in quotes. Probably from the last time that we reviewed windows project files.
