### ISSUE TITLE
Add support for an altappid entitlement property

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#70]
Replacing [BZ-116](http://bugs.openmama.org/show_bug.cgi?id=116)

We’ve found it very useful for application users to be able to configure the application name/id used for entitlements in a similar way to how they can for the username.

mama.c already supports this configuration parameter:

> mama.entitlement.altuserid

We would like an addition to mama.c to also support this parameter:

> mama.entitlement.altappid

This config parameter would be picked up by a call something like this in mama.c:

> altAppId   = properties_Get (gProperties, "mama.entitlement.altappid")

If present, the ‘altAppId’ would simply be used to set the application name:

> if(altAppId) mama_setApplicationName(altAppId)

This is useful so that the user and application name can be changed from their defaults by consistent means. Also, besides mamalistenc, most of the example programs delivered with openmama don’t provide a command line option for setting the application id, so it can’t easily be changed from the default value without modifying code and adding a mama_setApplicationName() call, which is a bit inconvenient.

**Comment by adriennea** [comment]
- I think it should be mama.application_id or mama.application.id  as mama_getApplicationName() would return value i.e. It is not just for entitlements. mama.entitlement.altuserd is used for entitlements only and the 'alt' part is to distinguish it from system user ID

- Whatever the parameter name, for completeness it should be extended to cover the application class as well.

- I've also thought it would be nicer to default to the binary name rather than 'MamaApplication' if an application ID is not set, but this may break backward compatibility for some apps and there is no platform independent way of doing it, so it would require a bit more work.

**Comment by fquinner** [comment]
Please submit a PR if this is something you're interested in contributing.
