### ISSUE TITLE
MamaPublisher: Overloaded MamaPublisher create method

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#71]
Replacing [BZ-165] (http://bugs.openmama.org/show_bug.cgi?id=165)

patch for MamaPublisher create

Added flexibility to the mamaPublisher create method where it accepts a source parameter in case some bridges don't support the source being included in the topic variable.

[Overloaded-MamaPublisher-create-method (1).txt](https://github.com/OpenMAMA/OpenMAMA/files/22561/Overloaded-MamaPublisher-create-method.1.txt)

**Comment by fquinner** [comment]
Was already added as part of #128 Reed's publisher changes
