### ISSUE TITLE
Extend the ignoredups option to include recaps

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#72]
Replacing [BZ-200] (http://bugs.openmama.org/show_bug.cgi?id=200)

Currently the ignoredups DQStrategy will only drop updates with a seqnum number lower than expected.
However in some cases it may be preferable to drop old recaps as well. 
This option has been extended to cover these cases.

[0001-MAMAC-Extend-the-ignoredups-option-to-include-recaps.txt](https://github.com/OpenMAMA/OpenMAMA/files/22566/0001-MAMAC-Extend-the-ignoredups-option-to-include-recaps.txt)

**Comment by MattMulhern** [comment]
This was already committed into next a while ago (f059102dd67fa0c2f307d72cd0ee68d2af63d422). Closing off.
