### ISSUE TITLE
example app executables created via windows openmama build are misnamed: openmamalistenc

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#73]
Replacing [BZ-32] (http://bugs.openmama.org/show_bug.cgi?id=32)

Environment - Win VC 8 64 bit 

The directory containing the executables & dlls contains standard example app prefixed with "open", though mamachurnc and mamaconsumerc are OK

C:\var\userspace\cfield\OpenMAMAPhase3rc7\openmama\openmama\openmama>ls x64\release
avis.dll                  mamachurnc.pdb
bookselftest.exe          mamachurncpp.exe
bookselftest.pdb          mamachurncpp.pdb
libmamaavisimplmd.dll     mamaconsumerc.exe
libmamaavisimplmd.exp     mamaconsumerc.pdb
libmamaavisimplmd.lib     mamapingpong_replycpp.exe
libmamaavisimplmd.pdb     mamapingpong_replycpp.pdb
libmamaavismsgimplmd.dll  openmamaftmemberc.exe
libmamaavismsgimplmd.exp  openmamaftmemberc.pdb
libmamaavismsgimplmd.lib  openmamaftmembercpp.exe
libmamaavismsgimplmd.pdb  openmamaftmembercpp.pdb
libmamacmd.dll            openmamainboxc.exe
libmamacmd.exp            openmamainboxc.pdb
libmamacmd.lib            openmamainboxcpp.exe
libmamacmd.pdb            openmamainboxcpp.pdb
libmamacppmd.dll          openmamaioc.exe
libmamacppmd.exp          openmamaioc.pdb
libmamacppmd.ilk          openmamaiocpp.exe
libmamacppmd.lib          openmamaiocpp.pdb
libmamacppmd.pdb          openmamalistenc.exe
libmamajni.dll            openmamalistenc.pdb
libmamajni.exp            openmamalistencpp.exe
libmamajni.lib            openmamalistencpp.pdb
libmamajni.pdb            openmamamsgpublishercpp.exe
libmamdabookmd.dll        openmamamsgpublishercpp.pdb
libmamdabookmd.exp        openmamamultisubscriberc.exe
libmamdabookmd.lib        openmamamultisubscriberc.pdb
libmamdabookmd.pdb        openmamaproxyc.exe
libmamdamd.dll            openmamaproxyc.pdb
libmamdamd.exp            openmamaproxycpp.exe
libmamdamd.lib            openmamaproxycpp.pdb
libmamdamd.pdb            openmamapublisherc.exe
libmamdanewsmdd.dll       openmamapublisherc.pdb
libmamdanewsmdd.exp       openmamapublishercpp.exe
libmamdanewsmdd.lib       openmamapublishercpp.pdb
libmamdanewsmdd.pdb       openmamasubscriberc.exe
libmamdaoptionsmd.dll     openmamasubscriberc.pdb
libmamdaoptionsmd.exp     openmamasubscribercpp.exe
libmamdaoptionsmd.lib     openmamasubscribercpp.pdb
libmamdaoptionsmd.pdb     openmamasymbollistsubscriberc.exe
libwombatcommoncppmd.dll  openmamasymbollistsubscriberc.pdb
libwombatcommoncppmd.pdb  openmamasymbollistsubscribercpp.exe
libwombatcommonmd.dll     openmamasymbollistsubscribercpp.pdb
libwombatcommonmd.exp     quoteselftest.exe
libwombatcommonmd.lib     quoteselftest.pdb
libwombatcommonmd.pdb     tradeselftest.exe
mamachurnc.exe            tradeselftest.pdb

Shouldn't be a problem with the SCons builds on Windows, but may still be problematic with the VS builds.

**Comment by MattMulhern** [comment]
Possibly resolved but needs checking.

**Comment by MattMulhern** [comment]
code changes being tracked on #132, but leaving this here to track issue separately.

**Comment by MattMulhern** [comment]
seems to already have been fixed:
```
D:\mmulhern\openmama\vs_update>ls x64\Debug
libmamac.exp               mamaiocpp.pdb
libmamac.lib               mamalistenc.exe
libmamac.pdb               mamalistenc.ilk
libmamacmdd.dll            mamalistenc.pdb
libmamacmdd.ilk            mamalistencpp.exe
libmamacpp.exp             mamalistencpp.ilk
libmamacpp.lib             mamalistencpp.pdb
libmamacpp.pdb             mamamsgpublishercpp.exe
libmamacppmdd.dll          mamamsgpublishercpp.ilk
libmamacppmdd.ilk          mamamsgpublishercpp.pdb
libwombatcommonc.exp       mamamultisubscriberc.exe
libwombatcommonc.lib       mamamultisubscriberc.ilk
libwombatcommonc.pdb       mamamultisubscriberc.pdb
libwombatcommoncpp.exp     mamaproxyc.exe
libwombatcommoncpp.lib     mamaproxyc.ilk
libwombatcommoncpp.pdb     mamaproxyc.pdb
libwombatcommoncppmdd.dll  mamaproxycpp.exe
libwombatcommoncppmdd.ilk  mamaproxycpp.ilk
libwombatcommonmdd.dll     mamaproxycpp.pdb
libwombatcommonmdd.ilk     mamapublisherc.exe
libwombatcommonmdd.map     mamapublisherc.ilk
mamaftmemberc.exe          mamapublisherc.pdb
mamaftmemberc.ilk          mamapublishercpp.exe
mamaftmemberc.pdb          mamapublishercpp.ilk
mamaftmembercpp.exe        mamapublishercpp.pdb
mamaftmembercpp.ilk        mamasubscriberc.exe
mamaftmembercpp.pdb        mamasubscriberc.ilk
mamainboxc.exe             mamasubscriberc.pdb
mamainboxc.ilk             mamasubscribercpp.exe
mamainboxc.pdb             mamasubscribercpp.ilk
mamainboxcpp.exe           mamasubscribercpp.pdb
mamainboxcpp.ilk           mamasymbollistsubscriberc.exe
mamainboxcpp.pdb           mamasymbollistsubscriberc.ilk
mamaioc.exe                mamasymbollistsubscriberc.pdb
mamaioc.ilk                mamasymbollistsubscribercpp.exe
mamaioc.pdb                mamasymbollistsubscribercpp.ilk
mamaiocpp.exe              mamasymbollistsubscribercpp.pdb
mamaiocpp.ilk
```
Closing this off for now unless anything else crops up.
