### ISSUE TITLE
UNITTESTS: Changes to the CHECK_NON_IMPLEMENTED macros to allow dynamic specification

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#75]
Replacing [BZ-56] (http://bugs.openmama.org/show_bug.cgi?id=56)

Unittest Not implemented macro changes patch

Changing the CHECK_NON_IMPLEMENTED_* macros to allow users to specify the level of strictness at the command line rather than during compile time.

The command line arguments come in the following forms:
--allow-not-implemented <level>
-n <level>

Where level is one of (case insensitive):
None        - No tests should pass when they return MAMA_STATUS_NOT_IMPLEMENTED
Optional    - Only tests denoted as optional pass when they return MAMA_STATUS_NOT_IMPLEMENTED
Recommended - Only tests denoted as optional or recommended pass when they return MAMA_STATUS_NOT_IMPLEMENTED
All         - All tests denoted as optional, recommended or mandatory pass when they return MAMA_STATUS_NOT_IMPLEMENTED 
Mandatory   - Same behaviour as 'All'

The default level (when no command line is passed) is 'Optional'.

At present the check only impacts those which have the macro enabled, though eventually this should cover the majority of tests.

[0001-UNITTESTS-Changes-to-the-CHECK_NON_IMPLEMENTED-macro.txt](https://github.com/OpenMAMA/OpenMAMA/files/22574/0001-UNITTESTS-Changes-to-the-CHECK_NON_IMPLEMENTED-macro.txt)

**Comment by fquinner** [comment]
Now tracked in pull request #122.
