### ISSUE TITLE
[BZ-28] MAMA: openmama build on windows, java client with avis, gives an UnsatisfiedLinkError

### ISSUE THREAD

**Issue by MattMulhern** [OpenMAMA/OpenMAMA#82]
replacing [bz-28](http://bugs.openmama.org/show_bug.cgi?id=28)
> Environment - Windows VC 8 64bit 
> 
> opensource build on windows, java client for avis, gives an UnsatisfiedLinkError:
> 
> opensource on Linux, java client with avis MamaPublisherJava and MamaSubscriberJava run fine
> 
> C:\var\userspace\cfield\OpenMAMAPhase3rc10VC8NewJNI\openmama\mama\jni>java com.wombat.mama.examples.MamaPublisherJava -m avis -tport avis_cfield
> Starting Publisher with:
>    topic:              MAMA_TOPIC
>    inbound topic:      MAMA_INBOUND_TOPIC
>    interval            1.0
>    transport:          avis_cfield
> 
> Exception in thread "main" java.lang.UnsatisfiedLinkError: no mamajni in java.library.path
>         at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1682)
>         at java.lang.Runtime.loadLibrary0(Runtime.java:822)
>         at java.lang.System.loadLibrary(System.java:993)
>         at com.wombat.mama.Mama.<clinit>(Mama.java:52)
>         at com.wombat.mama.examples.MamaPublisherJava.initializeMama(MamaPublisherJava.java:80)
>         at com.wombat.mama.examples.MamaPublisherJava.main(MamaPublisherJava.java:259)
> 
> C:\var\userspace\cfield\OpenMAMAPhase3rc10VC8NewJNI\openmama\mama\jni>java com.wombat.mama.examples.MamaSubscriberJava -m avis -tport avis_cfield
> Starting Publisher with:
>    middleware:         avis
>    topic:              MAMA_TOPIC
>    transport:          avis_cfield
> 
> Exception in thread "main" java.lang.UnsatisfiedLinkError: no mamajni in java.library.path
>         at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1682)
>         at java.lang.Runtime.loadLibrary0(Runtime.java:822)
>         at java.lang.System.loadLibrary(System.java:993)
>         at com.wombat.mama.Mama.<clinit>(Mama.java:52)
>         at com.wombat.mama.examples.MamaSubscriberJava.initializeMama(MamaSubscriberJava.java:240)
>         at com.wombat.mama.examples.MamaSubscriberJava.main(MamaSubscriberJava.java:62)
> 
> mamajni vcproj file builds mamajni.dll with wrong name
> 
> It specified output as libmamajni.dll instead of mamajni.dll.

**Comment by MattMulhern** [comment]
SConscript.win:
```
target = 'mamajni'
```
SConscript:
```
target = 'libmamajni'
```
mamajni.vcproj
```
			<Tool
				Name="VCLinkerTool"
				OutputFile="$(OutDir)\libmamajni.dll"
				LinkIncremental="2"
				GenerateDebugInformation="true"
				SubSystem="2"
				TargetMachine="17"

[...]
			<Tool
				Name="VCLinkerTool"
				OutputFile="$(OutDir)\libmamajni.dll"
				LinkIncremental="1"
				GenerateDebugInformation="true"
				SubSystem="2"
				OptimizeReferences="2"
				EnableCOMDATFolding="2"
				TargetMachine="17"

```

**Comment by fquinner** [comment]
Looks like this was fixed for everything except for Visual Studio project files on windows and only for 64-bit. According to a comment in the scons scripts:

```
# Java, when loading the mamajni dll, expects it to be called mamajni.dll, without
# the lib prefix or 'md/mdd' suffix. Therefore, we cannot use the InstallLibrary
# method used elsewhere.
```
Small fix will correct.

**Comment by fquinner** [comment]
Now tracked in pull request #119
