### ISSUE TITLE
Throw in MamaTransport destructor

### ISSUE THREAD

**Issue by svtesan** [OpenMAMA/OpenMAMA#83]
MamaTransport destructor throws if the object is just created and destroyed without initializing it:

     MamaTransport::~MamaTransport (void) 
    {
        if (mPimpl)
        {
		    if ( mamaInternal_getCatchCallbackExceptions() && mPimpl->mCallback)
		    {
			    delete mPimpl->mCallback;
		    }
            if (mPimpl->mDeleteCTransport)
            {
                =>mamaTry (mamaTransport_destroy (mTransport));<=
            }
            delete mPimpl;
            mPimpl = NULL;
        }
    }

`mamaTransport_destory` fails because the transport was never initialized in the first place. but we should not be using `mamaTry()` in destructor.

To reproduce:

    void test_transport_crash()
    {
        MamaTransport t;
    }

**Comment by fquinner** [comment]
Already fixed: https://github.com/OpenMAMA/OpenMAMA/commit/92c0398c589fa04d5b3ab47d854f1e8691ce998f#diff-4930f77fd97f9c1767647148297df1e3
