### ISSUE TITLE
MAMA: Java queue group missing getNumberOfQueues method

### ISSUE THREAD

**Issue by reed-jpm-alpert** [OpenMAMA/OpenMAMA#89]
MAMA: Java queue group missing getNumberOfQueues method

For MamaQueueGroup.java there is a missing getNumberOfQueues method. Also add unit test.

Will add pull request.

**Comment by MattMulhern** [comment]
Hi reed,
Any updates on this?

Thanks,
Matt

**Comment by reed-jpm-alpert** [comment]
I found this code in the next branch for OM github, must have been in an earlier pull request. I'll close this. Thanks.

**Comment by reed-jpm-alpert** [comment]
Hi Frank,

I found this new method in the OM github next branch, so it must have been in an earlier pull request.
I closed the issue.

Thanks,

Reed.

________________________________
Reed Alpert | Corporate & Investment Bank | Market Data Services | J.P. Morgan | 4 Metrotech Center, 23rd Floor, Brooklyn, NY 11245 | T: 718.242.5198  | M: 917.414.4613 | reed.alpert@jpmorgan.com<mailto:reed.alpert@jpmorgan.com>
Alternate Contact:  CIB Market Data Services Engineers | CIB_Market_Data_Services_Engineers@restricted.chase.com<mailto:CIB_Market_Data_Services_Engineers@restricted.chase.com>
