### ISSUE TITLE
Enforcing field type on publish

### ISSUE THREAD

**Issue by MattMulhern** [OpenMAMA/OpenMAMA#9]
Details on [mail thread](http://lists.openmama.org/pipermail/openmama-dev/2014-September/001323.html).

Original poster has asked if there is a mechanism by which they can check that the data type of a field being published matches that stored in the dictionary - they are looking for an option which allows them to implement this across their publishers, without having to trust developers to implement checks themselves. after some discussion a general agreement that baking this into payloads/bridges isn't the right place was made, and that it should go into the C layer (so other languages don't need changed). The options ultimately are either within mamaMsg add/update\* calls, or within the mamaPublisher.send, with pros and cons to each.

Ultimately the proposed solution would be to add a hook to mamaPublisher.send which can then be used  by client libraries to perform whatever checks/manipulations they require.

**Comment by fquinner** [comment]
See: https://github.com/OpenMAMA/OpenMAMA/blob/next/mama/c_cpp/src/c/plugin.h#L28
It can be done now with a publisher plugin.
