### ISSUE TITLE
MAMA: Add method to get transport from publisher impl

### ISSUE THREAD

**Issue by reed-jpm-alpert** [OpenMAMA/OpenMAMA#90]
For publisher plugins add a method to get the transport from the publisher impl. This allows plugins to get the transport when getting called with the publisher in PublisherFieldCheckMamaPlugin_publisherPreSendHook().

I will submit pull request for this.

**Comment by MattMulhern** [comment]
Superseded by pull request #91.
Closing off as per issue [guidelines](https://github.com/OpenMAMA/OpenMAMA/wiki/Raising-Issues)
