### ISSUE TITLE
SCONS: add Linux target for 32-bit build

### ISSUE THREAD

**Issue by reed-jpm-alpert** [OpenMAMA/OpenMAMA#92]
Add scons target for Linux 32-bit build. Also add FLAGS for GNU compilers. Also add CC and CXX from environment to use an alternative version of the GNU compiler.

Will submit patch for this.

**Comment by MattMulhern** [comment]
Superseded by #93. Closing off as duplicate.

Issues are unnecessary if pull request is being opened at the same time. Please see [documentation](https://github.com/OpenMAMA/OpenMAMA/wiki/Raising-Issues)
