### ISSUE TITLE
Scons build on windows does not check for presence of flex

### ISSUE THREAD

**Issue by fquinner** [OpenMAMA/OpenMAMA#99]
Instead it gives an obscure error if it isn't set up:

scons: *** While building `['src\\c\\lex.yy.o']' from `['D:\\SourceExternal\\fquinner\\OpenMAMA\\common\\c_cpp\\src\\c\\properties.l']': Don't know how to build from a source file with suffix `.l'.  Expected a suffix in this list: ['.c', '.C', '.cc', '.cpp', '.cxx', '.c++', '.C++', '.f', '.for', '.ftn', '.F', '.FOR', '.FTN', '.fpp', '.FPP', '.f77', '.F77', '.f90', '.F90', '.f95', '.F95', '.f03', '.F03', '.f08', '.F08', '.s', '.asm', '.ASM', '.S', '.spp', '.SPP', '.sx', '.d'].

**Comment by MattMulhern** [comment]
closing this off as relevant PR has been approved.
